--migrate:up 

INSERT INTO studios (id, name) VALUES (1,'100studio');
INSERT INTO studios (id, name) VALUES (2,'10Gauge');
INSERT INTO studios (id, name) VALUES (3,'1IN');
INSERT INTO studios (id, name) VALUES (4,'2:10 AM Animation');
INSERT INTO studios (id, name) VALUES (5,'33 Collective');
INSERT INTO studios (id, name) VALUES (6,'5 Inc.');
INSERT INTO studios (id, name) VALUES (7,'6pucks');
INSERT INTO studios (id, name) VALUES (8,'7doc');
INSERT INTO studios (id, name) VALUES (9,'81 Produce');
INSERT INTO studios (id, name) VALUES (10,'8bit');
INSERT INTO studios (id, name) VALUES (11,'A-1 Pictures');
INSERT INTO studios (id, name) VALUES (12,'A-Line');
INSERT INTO studios (id, name) VALUES (13,'A-Real');
INSERT INTO studios (id, name) VALUES (14,'A.C.G.T.');
INSERT INTO studios (id, name) VALUES (15,'Academy Productions');
INSERT INTO studios (id, name) VALUES (16,'ACC Production');
INSERT INTO studios (id, name) VALUES (17,'Acca effe');
INSERT INTO studios (id, name) VALUES (18,'ACiD FiLM');
INSERT INTO studios (id, name) VALUES (19,'Actas');
INSERT INTO studios (id, name) VALUES (20,'Adonero');
INSERT INTO studios (id, name) VALUES (21,'Agent 21');
INSERT INTO studios (id, name) VALUES (22,'AHA Entertainment');
INSERT INTO studios (id, name) VALUES (23,'Ai Si Animation Studio');
INSERT INTO studios (id, name) VALUES (24,'Ai Yume Mai');
INSERT INTO studios (id, name) VALUES (25,'AIC');
INSERT INTO studios (id, name) VALUES (26,'AIC ASTA');
INSERT INTO studios (id, name) VALUES (27,'AIC Build');
INSERT INTO studios (id, name) VALUES (28,'AIC Classic');
INSERT INTO studios (id, name) VALUES (29,'AIC Frontier');
INSERT INTO studios (id, name) VALUES (30,'AIC PLUS+');
INSERT INTO studios (id, name) VALUES (31,'AIC Project');
INSERT INTO studios (id, name) VALUES (32,'AIC Spirits');
INSERT INTO studios (id, name) VALUES (33,'AIC Takarazuka');
INSERT INTO studios (id, name) VALUES (34,'Aiko');
INSERT INTO studios (id, name) VALUES (35,'AION Studio');
INSERT INTO studios (id, name) VALUES (36,'Aiti St.');
INSERT INTO studios (id, name) VALUES (37,'Ajia-do');
INSERT INTO studios (id, name) VALUES (38,'Akatsuki');
INSERT INTO studios (id, name) VALUES (39,'Albacrow');
INSERT INTO studios (id, name) VALUES (40,'Alfred Imageworks');
INSERT INTO studios (id, name) VALUES (41,'Alice Production');
INSERT INTO studios (id, name) VALUES (42,'Alpha Animation');
INSERT INTO studios (id, name) VALUES (43,'Amarcord');
INSERT INTO studios (id, name) VALUES (44,'AMGA');
INSERT INTO studios (id, name) VALUES (45,'Amineworks');
INSERT INTO studios (id, name) VALUES (46,'An DerCen');
INSERT INTO studios (id, name) VALUES (47,'Angle');
INSERT INTO studios (id, name) VALUES (48,'ANIDO FILM');
INSERT INTO studios (id, name) VALUES (49,'Anima');
INSERT INTO studios (id, name) VALUES (50,'Anima&Co.');
INSERT INTO studios (id, name) VALUES (51,'Animaruya');
INSERT INTO studios (id, name) VALUES (52,'animate Film');
INSERT INTO studios (id, name) VALUES (53,'Animation 21');
INSERT INTO studios (id, name) VALUES (54,'Animation 501');
INSERT INTO studios (id, name) VALUES (55,'Animation Do');
INSERT INTO studios (id, name) VALUES (56,'Animation Lab Japan');
INSERT INTO studios (id, name) VALUES (57,'Animation Planet');
INSERT INTO studios (id, name) VALUES (58,'Animation Staff Room');
INSERT INTO studios (id, name) VALUES (59,'Anime Antenna Iinkai');
INSERT INTO studios (id, name) VALUES (60,'Anime Beans');
INSERT INTO studios (id, name) VALUES (61,'Anime R');
INSERT INTO studios (id, name) VALUES (62,'Anime Tokyo');
INSERT INTO studios (id, name) VALUES (63,'Ankama Animations');
INSERT INTO studios (id, name) VALUES (64,'Annapuru');
INSERT INTO studios (id, name) VALUES (65,'Anon Pictures');
INSERT INTO studios (id, name) VALUES (66,'Anpro');
INSERT INTO studios (id, name) VALUES (67,'APPP');
INSERT INTO studios (id, name) VALUES (68,'AQUA ARIS');
INSERT INTO studios (id, name) VALUES (69,'Arch');
INSERT INTO studios (id, name) VALUES (70,'Arcs Create');
INSERT INTO studios (id, name) VALUES (71,'Arcturus');
INSERT INTO studios (id, name) VALUES (72,'ARCUS');
INSERT INTO studios (id, name) VALUES (73,'ARECT');
INSERT INTO studios (id, name) VALUES (74,'Ark');
INSERT INTO studios (id, name) VALUES (75,'Arms');
INSERT INTO studios (id, name) VALUES (76,'Artland');
INSERT INTO studios (id, name) VALUES (77,'Artmic');
INSERT INTO studios (id, name) VALUES (78,'Arvo Animation');
INSERT INTO studios (id, name) VALUES (79,'Asahi Production');
INSERT INTO studios (id, name) VALUES (80,'Ascension');
INSERT INTO studios (id, name) VALUES (81,'Ashi Productions');
INSERT INTO studios (id, name) VALUES (82,'ASK Animation Studio');
INSERT INTO studios (id, name) VALUES (83,'Asmik Ace');
INSERT INTO studios (id, name) VALUES (84,'asread.');
INSERT INTO studios (id, name) VALUES (85,'Assez Finaud Fabric');
INSERT INTO studios (id, name) VALUES (86,'Asura Film');
INSERT INTO studios (id, name) VALUES (87,'AT-2');
INSERT INTO studios (id, name) VALUES (88,'AtelierPontdarc');
INSERT INTO studios (id, name) VALUES (89,'Atorie A.B.C.');
INSERT INTO studios (id, name) VALUES (90,'Atti Production');
INSERT INTO studios (id, name) VALUES (91,'Au Praxinoscope');
INSERT INTO studios (id, name) VALUES (92,'Aubec');
INSERT INTO studios (id, name) VALUES (93,'Aurora Animation');
INSERT INTO studios (id, name) VALUES (94,'Aurum Production');
INSERT INTO studios (id, name) VALUES (95,'Automatic Flowers Studio');
INSERT INTO studios (id, name) VALUES (96,'AXsiZ');
INSERT INTO studios (id, name) VALUES (97,'Azeta Pictures');
INSERT INTO studios (id, name) VALUES (98,'B&T');
INSERT INTO studios (id, name) VALUES (99,'B.CMAY PICTURES');
INSERT INTO studios (id, name) VALUES (100,'Bakken Record');
INSERT INTO studios (id, name) VALUES (101,'Bandai Namco Filmworks');
INSERT INTO studios (id, name) VALUES (102,'Bandai Namco Pictures');
INSERT INTO studios (id, name) VALUES (103,'Bandai Spirits');
INSERT INTO studios (id, name) VALUES (104,'Bandai Visual');
INSERT INTO studios (id, name) VALUES (105,'Barnum Studio');
INSERT INTO studios (id, name) VALUES (106,'Beat Frog');
INSERT INTO studios (id, name) VALUES (107,'Bebow');
INSERT INTO studios (id, name) VALUES (108,'Bee Media');
INSERT INTO studios (id, name) VALUES (109,'Bee Train');
INSERT INTO studios (id, name) VALUES (110,'Beijing Enlight Pictures');
INSERT INTO studios (id, name) VALUES (111,'Beijing Huihuang Animation Company');
INSERT INTO studios (id, name) VALUES (112,'Benlai Pictures');
INSERT INTO studios (id, name) VALUES (113,'BeSTACK');
INSERT INTO studios (id, name) VALUES (114,'Bibury Animation CG');
INSERT INTO studios (id, name) VALUES (115,'Bibury Animation Studios');
INSERT INTO studios (id, name) VALUES (116,'Big Bang');
INSERT INTO studios (id, name) VALUES (117,'Big Firebird Culture');
INSERT INTO studios (id, name) VALUES (118,'Big Wing');
INSERT INTO studios (id, name) VALUES (119,'Bigcat Studio');
INSERT INTO studios (id, name) VALUES (120,'Blade');
INSERT INTO studios (id, name) VALUES (121,'Blue bread');
INSERT INTO studios (id, name) VALUES (122,'Blue Cat');
INSERT INTO studios (id, name) VALUES (123,'Blue Note');
INSERT INTO studios (id, name) VALUES (124,'Bones');
INSERT INTO studios (id, name) VALUES (125,'Borutong');
INSERT INTO studios (id, name) VALUES (126,'Bouncy');
INSERT INTO studios (id, name) VALUES (127,'Boyan Pictures');
INSERT INTO studios (id, name) VALUES (128,'Brain''s Base');
INSERT INTO studios (id, name) VALUES (129,'BreakBottle');
INSERT INTO studios (id, name) VALUES (130,'Brians Film');
INSERT INTO studios (id, name) VALUES (131,'Bridge');
INSERT INTO studios (id, name) VALUES (132,'Brio Animation');
INSERT INTO studios (id, name) VALUES (133,'Buemon');
INSERT INTO studios (id, name) VALUES (134,'BUG FILMS');
INSERT INTO studios (id, name) VALUES (135,'BUILD DREAM');
INSERT INTO studios (id, name) VALUES (136,'BYMENT');
INSERT INTO studios (id, name) VALUES (137,'C and R');
INSERT INTO studios (id, name) VALUES (138,'C&S Production');
INSERT INTO studios (id, name) VALUES (139,'C-Station');
INSERT INTO studios (id, name) VALUES (140,'C2C');
INSERT INTO studios (id, name) VALUES (141,'Cafe de Jeilhouse');
INSERT INTO studios (id, name) VALUES (142,'Calf Studio');
INSERT INTO studios (id, name) VALUES (143,'CANDY BOX');
INSERT INTO studios (id, name) VALUES (144,'CANON RECORDINGS');
INSERT INTO studios (id, name) VALUES (145,'Caviar');
INSERT INTO studios (id, name) VALUES (146,'CCTV Animation');
INSERT INTO studios (id, name) VALUES (147,'Central Animation Studio');
INSERT INTO studios (id, name) VALUES (148,'CG Year');
INSERT INTO studios (id, name) VALUES (149,'CGCG Studio');
INSERT INTO studios (id, name) VALUES (150,'Changchun Unity of Knowledge and Action Animation');
INSERT INTO studios (id, name) VALUES (151,'Chaos Project');
INSERT INTO studios (id, name) VALUES (152,'Charaction');
INSERT INTO studios (id, name) VALUES (153,'Children''s Playground Entertainment');
INSERT INTO studios (id, name) VALUES (154,'Chiptune');
INSERT INTO studios (id, name) VALUES (155,'CHOCOLATE');
INSERT INTO studios (id, name) VALUES (156,'Chongzhuo Animation');
INSERT INTO studios (id, name) VALUES (157,'Chosen');
INSERT INTO studios (id, name) VALUES (158,'ChuChu');
INSERT INTO studios (id, name) VALUES (159,'Circle Tribute');
INSERT INTO studios (id, name) VALUES (160,'Circus Production');
INSERT INTO studios (id, name) VALUES (161,'CLAP');
INSERT INTO studios (id, name) VALUES (162,'Cloud Art');
INSERT INTO studios (id, name) VALUES (163,'Cloud Hearts');
INSERT INTO studios (id, name) VALUES (164,'CloverWorks');
INSERT INTO studios (id, name) VALUES (165,'CMAY Animation');
INSERT INTO studios (id, name) VALUES (166,'Coastline Animation Studio');
INSERT INTO studios (id, name) VALUES (167,'Code');
INSERT INTO studios (id, name) VALUES (168,'cogitoworks');
INSERT INTO studios (id, name) VALUES (169,'Collaboration Works');
INSERT INTO studios (id, name) VALUES (170,'Colored Pencil Animation');
INSERT INTO studios (id, name) VALUES (171,'Colored Pencil Animation Japan');
INSERT INTO studios (id, name) VALUES (172,'CoMix Wave Films');
INSERT INTO studios (id, name) VALUES (173,'Comma Studio');
INSERT INTO studios (id, name) VALUES (174,'Composition Inc.');
INSERT INTO studios (id, name) VALUES (175,'Concept Films');
INSERT INTO studios (id, name) VALUES (176,'Congrong Film');
INSERT INTO studios (id, name) VALUES (177,'Congzhuo Animation');
INSERT INTO studios (id, name) VALUES (178,'Connect');
INSERT INTO studios (id, name) VALUES (179,'Contrail');
INSERT INTO studios (id, name) VALUES (180,'Craftar Studios');
INSERT INTO studios (id, name) VALUES (181,'Creative Power Entertaining');
INSERT INTO studios (id, name) VALUES (182,'Creators Dot Com');
INSERT INTO studios (id, name) VALUES (183,'Creators in Pack');
INSERT INTO studios (id, name) VALUES (184,'Creatures Inc.');
INSERT INTO studios (id, name) VALUES (185,'CUCURI');
INSERT INTO studios (id, name) VALUES (186,'Cutie Bee');
INSERT INTO studios (id, name) VALUES (187,'CyberConnect2');
INSERT INTO studios (id, name) VALUES (188,'Cyclone Graphics');
INSERT INTO studios (id, name) VALUES (189,'CygamesPictures');
INSERT INTO studios (id, name) VALUES (190,'D & D Pictures');
INSERT INTO studios (id, name) VALUES (191,'D.A.S.T.');
INSERT INTO studios (id, name) VALUES (192,'d00r works');
INSERT INTO studios (id, name) VALUES (193,'Daewon Media');
INSERT INTO studios (id, name) VALUES (194,'Dai-Ichi Douga');
INSERT INTO studios (id, name) VALUES (195,'Dancing CG Studio');
INSERT INTO studios (id, name) VALUES (196,'DandeLion Animation Studio');
INSERT INTO studios (id, name) VALUES (197,'Dangun Pictures');
INSERT INTO studios (id, name) VALUES (198,'Darts');
INSERT INTO studios (id, name) VALUES (199,'Datama Film');
INSERT INTO studios (id, name) VALUES (200,'Daume');
INSERT INTO studios (id, name) VALUES (201,'David Production');
INSERT INTO studios (id, name) VALUES (202,'Dawn Animation');
INSERT INTO studios (id, name) VALUES (203,'DAX Production');
INSERT INTO studios (id, name) VALUES (204,'Dazzling Star');
INSERT INTO studios (id, name) VALUES (205,'DC Impression Vision');
INSERT INTO studios (id, name) VALUES (206,'Deck');
INSERT INTO studios (id, name) VALUES (207,'Decovocal');
INSERT INTO studios (id, name) VALUES (208,'Delight Animation');
INSERT INTO studios (id, name) VALUES (209,'Delpic');
INSERT INTO studios (id, name) VALUES (210,'Digital Frontier');
INSERT INTO studios (id, name) VALUES (211,'Digital Media Lab');
INSERT INTO studios (id, name) VALUES (212,'Digital Network Animation');
INSERT INTO studios (id, name) VALUES (213,'Diomedéa');
INSERT INTO studios (id, name) VALUES (214,'Directions');
INSERT INTO studios (id, name) VALUES (215,'Djinn Power');
INSERT INTO studios (id, name) VALUES (216,'DLE');
INSERT INTO studios (id, name) VALUES (217,'DMM.futureworks');
INSERT INTO studios (id, name) VALUES (218,'Doga Kobo');
INSERT INTO studios (id, name) VALUES (219,'DOGA Productions');
INSERT INTO studios (id, name) VALUES (220,'domerica');
INSERT INTO studios (id, name) VALUES (221,'Dongwoo A&E');
INSERT INTO studios (id, name) VALUES (222,'Dongyang Animation');
INSERT INTO studios (id, name) VALUES (223,'DR Movie');
INSERT INTO studios (id, name) VALUES (224,'Drawing and Manual');
INSERT INTO studios (id, name) VALUES (225,'DRAWIZ');
INSERT INTO studios (id, name) VALUES (226,'Dream Entertainment');
INSERT INTO studios (id, name) VALUES (227,'Drive');
INSERT INTO studios (id, name) VALUES (228,'drop');
INSERT INTO studios (id, name) VALUES (229,'Durufix');
INSERT INTO studios (id, name) VALUES (230,'dwarf');
INSERT INTO studios (id, name) VALUES (231,'Dyna Method');
INSERT INTO studios (id, name) VALUES (232,'Dynamic Planning');
INSERT INTO studios (id, name) VALUES (233,'Dynamo Pictures');
INSERT INTO studios (id, name) VALUES (234,'E&G Films');
INSERT INTO studios (id, name) VALUES (235,'E&H Production');
INSERT INTO studios (id, name) VALUES (236,'Eallin');
INSERT INTO studios (id, name) VALUES (237,'Earth Design Works');
INSERT INTO studios (id, name) VALUES (238,'East Fish Studio');
INSERT INTO studios (id, name) VALUES (239,'Echo');
INSERT INTO studios (id, name) VALUES (240,'Echoes');
INSERT INTO studios (id, name) VALUES (241,'EDP graphic works');
INSERT INTO studios (id, name) VALUES (242,'Egg');
INSERT INTO studios (id, name) VALUES (243,'Egg Firm');
INSERT INTO studios (id, name) VALUES (244,'Eiken');
INSERT INTO studios (id, name) VALUES (245,'EKACHI EPILKA');
INSERT INTO studios (id, name) VALUES (246,'Ekakiya');
INSERT INTO studios (id, name) VALUES (247,'Ekura Animal');
INSERT INTO studios (id, name) VALUES (248,'Emon');
INSERT INTO studios (id, name) VALUES (249,'EMT Squared');
INSERT INTO studios (id, name) VALUES (250,'Encourage Films');
INSERT INTO studios (id, name) VALUES (251,'ENGI');
INSERT INTO studios (id, name) VALUES (252,'Enishiya');
INSERT INTO studios (id, name) VALUES (253,'Enjin Productions');
INSERT INTO studios (id, name) VALUES (254,'Enzo Animation');
INSERT INTO studios (id, name) VALUES (255,'EOEO System');
INSERT INTO studios (id, name) VALUES (256,'Eshoya Honpo');
INSERT INTO studios (id, name) VALUES (257,'Ether Kitten');
INSERT INTO studios (id, name) VALUES (258,'evg');
INSERT INTO studios (id, name) VALUES (259,'Executive Decision');
INSERT INTO studios (id, name) VALUES (260,'Ezόla');
INSERT INTO studios (id, name) VALUES (261,'Fantawild Animation');
INSERT INTO studios (id, name) VALUES (262,'Fanworks');
INSERT INTO studios (id, name) VALUES (263,'feel.');
INSERT INTO studios (id, name) VALUES (264,'Felix Film');
INSERT INTO studios (id, name) VALUES (265,'Fengyun Animation');
INSERT INTO studios (id, name) VALUES (266,'Fenz');
INSERT INTO studios (id, name) VALUES (267,'Fever Creations');
INSERT INTO studios (id, name) VALUES (268,'Fifth Avenue');
INSERT INTO studios (id, name) VALUES (269,'Filmlink International');
INSERT INTO studios (id, name) VALUES (270,'FILMONY');
INSERT INTO studios (id, name) VALUES (271,'FIREBUG');
INSERT INTO studios (id, name) VALUES (272,'flag Co.');
INSERT INTO studios (id, name) VALUES (273,'FLAGSHIP LINE');
INSERT INTO studios (id, name) VALUES (274,'Flat Studio');
INSERT INTO studios (id, name) VALUES (275,'Flavors Soft');
INSERT INTO studios (id, name) VALUES (276,'Flint Sugar');
INSERT INTO studios (id, name) VALUES (277,'Flying Ship Studio');
INSERT INTO studios (id, name) VALUES (278,'Foch Films');
INSERT INTO studios (id, name) VALUES (279,'foodunited.');
INSERT INTO studios (id, name) VALUES (280,'FOREST Hunting One');
INSERT INTO studios (id, name) VALUES (281,'Four Some');
INSERT INTO studios (id, name) VALUES (282,'Front Line');
INSERT INTO studios (id, name) VALUES (283,'Frontier One');
INSERT INTO studios (id, name) VALUES (284,'Frontier Works');
INSERT INTO studios (id, name) VALUES (285,'Fuji TV');
INSERT INTO studios (id, name) VALUES (286,'Fukushima Gaina');
INSERT INTO studios (id, name) VALUES (287,'FUNNY MOVIE');
INSERT INTO studios (id, name) VALUES (288,'Future Planet');
INSERT INTO studios (id, name) VALUES (289,'G&G Entertainment');
INSERT INTO studios (id, name) VALUES (290,'G-angle');
INSERT INTO studios (id, name) VALUES (291,'G-Lam');
INSERT INTO studios (id, name) VALUES (292,'G.P Entertainment');
INSERT INTO studios (id, name) VALUES (293,'GA-CREW');
INSERT INTO studios (id, name) VALUES (294,'Gaina');
INSERT INTO studios (id, name) VALUES (295,'Gainax');
INSERT INTO studios (id, name) VALUES (296,'Gainax Kyoto');
INSERT INTO studios (id, name) VALUES (297,'Gakken');
INSERT INTO studios (id, name) VALUES (298,'Gakken Eigakyoku');
INSERT INTO studios (id, name) VALUES (299,'Gallop');
INSERT INTO studios (id, name) VALUES (300,'Gambit');
INSERT INTO studios (id, name) VALUES (301,'GANSIS');
INSERT INTO studios (id, name) VALUES (302,'Garden Culture');
INSERT INTO studios (id, name) VALUES (303,'GARDEN LODGE');
INSERT INTO studios (id, name) VALUES (304,'Garyuu Studio');
INSERT INTO studios (id, name) VALUES (305,'Gathering');
INSERT INTO studios (id, name) VALUES (306,'GAV Video');
INSERT INTO studios (id, name) VALUES (307,'Geek Toys');
INSERT INTO studios (id, name) VALUES (308,'Gekkou');
INSERT INTO studios (id, name) VALUES (309,'GEMBA');
INSERT INTO studios (id, name) VALUES (310,'Genco');
INSERT INTO studios (id, name) VALUES (311,'General Entertainment');
INSERT INTO studios (id, name) VALUES (312,'Geno Studio');
INSERT INTO studios (id, name) VALUES (313,'GIFTanimation');
INSERT INTO studios (id, name) VALUES (314,'Giga Production');
INSERT INTO studios (id, name) VALUES (315,'Ginga Ya');
INSERT INTO studios (id, name) VALUES (316,'GoHands');
INSERT INTO studios (id, name) VALUES (317,'Gonzino');
INSERT INTO studios (id, name) VALUES (318,'Gonzo');
INSERT INTO studios (id, name) VALUES (319,'Gosay Studio');
INSERT INTO studios (id, name) VALUES (320,'Goto Inc.');
INSERT INTO studios (id, name) VALUES (321,'Graphinica');
INSERT INTO studios (id, name) VALUES (322,'Gravity Well');
INSERT INTO studios (id, name) VALUES (323,'Green Monster Team');
INSERT INTO studios (id, name) VALUES (324,'Griot Groove');
INSERT INTO studios (id, name) VALUES (325,'GRIZZLY');
INSERT INTO studios (id, name) VALUES (326,'Grom');
INSERT INTO studios (id, name) VALUES (327,'Group TAC');
INSERT INTO studios (id, name) VALUES (328,'Grouper Productions');
INSERT INTO studios (id, name) VALUES (329,'GUMBLAB');
INSERT INTO studios (id, name) VALUES (330,'Gunners');
INSERT INTO studios (id, name) VALUES (331,'Guo Pengzi Studio');
INSERT INTO studios (id, name) VALUES (332,'Guton Animation Studio');
INSERT INTO studios (id, name) VALUES (333,'Gyorai Eizo Inc.');
INSERT INTO studios (id, name) VALUES (334,'Hai An Xian Donghua Gongzuo Shi');
INSERT INTO studios (id, name) VALUES (335,'Hal Film Maker');
INSERT INTO studios (id, name) VALUES (336,'Hananona Studio');
INSERT INTO studios (id, name) VALUES (337,'Hand to Mouse.');
INSERT INTO studios (id, name) VALUES (338,'Haneda xR Studio');
INSERT INTO studios (id, name) VALUES (339,'Haoliners Animation League');
INSERT INTO studios (id, name) VALUES (340,'Happy Elements');
INSERT INTO studios (id, name) VALUES (341,'happyproject');
INSERT INTO studios (id, name) VALUES (342,'Hayabusa Film');
INSERT INTO studios (id, name) VALUES (343,'Heart & Soul Animation');
INSERT INTO studios (id, name) VALUES (344,'HeART-BIT');
INSERT INTO studios (id, name) VALUES (345,'Heewon Entertainment');
INSERT INTO studios (id, name) VALUES (346,'helo.inc');
INSERT INTO studios (id, name) VALUES (347,'HIDEHOMARE');
INSERT INTO studios (id, name) VALUES (348,'High Energy Studio');
INSERT INTO studios (id, name) VALUES (349,'Himajin Planning');
INSERT INTO studios (id, name) VALUES (350,'Hiro Media');
INSERT INTO studios (id, name) VALUES (351,'HM Heros');
INSERT INTO studios (id, name) VALUES (352,'HMCH');
INSERT INTO studios (id, name) VALUES (353,'Hololive Production');
INSERT INTO studios (id, name) VALUES (354,'Hong Ying Animation');
INSERT INTO studios (id, name) VALUES (355,'Hoods Drifters Studio');
INSERT INTO studios (id, name) VALUES (356,'Hoods Entertainment');
INSERT INTO studios (id, name) VALUES (357,'Horannabi');
INSERT INTO studios (id, name) VALUES (358,'HoriPro');
INSERT INTO studios (id, name) VALUES (359,'HORNETS');
INSERT INTO studios (id, name) VALUES (360,'Hotline');
INSERT INTO studios (id, name) VALUES (361,'HOTZIPANG');
INSERT INTO studios (id, name) VALUES (362,'HS Pictures Studio');
INSERT INTO studios (id, name) VALUES (363,'Hu Po Donghua');
INSERT INTO studios (id, name) VALUES (364,'HuaDream');
INSERT INTO studios (id, name) VALUES (365,'HuaMei Animation');
INSERT INTO studios (id, name) VALUES (366,'Hurray!');
INSERT INTO studios (id, name) VALUES (367,'Husio Studio');
INSERT INTO studios (id, name) VALUES (368,'I was a Ballerina');
INSERT INTO studios (id, name) VALUES (369,'I-move');
INSERT INTO studios (id, name) VALUES (370,'I.Gzwei');
INSERT INTO studios (id, name) VALUES (371,'I.Toon');
INSERT INTO studios (id, name) VALUES (372,'Ice Butter');
INSERT INTO studios (id, name) VALUES (373,'Idea Factory');
INSERT INTO studios (id, name) VALUES (374,'Idol');
INSERT INTO studios (id, name) VALUES (375,'iDRAGONS Creative Studio');
INSERT INTO studios (id, name) VALUES (376,'IKK Room');
INSERT INTO studios (id, name) VALUES (377,'ILCA');
INSERT INTO studios (id, name) VALUES (378,'Image House');
INSERT INTO studios (id, name) VALUES (379,'Image Kei');
INSERT INTO studios (id, name) VALUES (380,'Imagestone Inc.');
INSERT INTO studios (id, name) VALUES (381,'Imagica');
INSERT INTO studios (id, name) VALUES (382,'Imagica Digitalscape');
INSERT INTO studios (id, name) VALUES (383,'Imagica Imageworks');
INSERT INTO studios (id, name) VALUES (384,'IMAGICA Lab.');
INSERT INTO studios (id, name) VALUES (385,'Imagin');
INSERT INTO studios (id, name) VALUES (386,'Imagineer');
INSERT INTO studios (id, name) VALUES (387,'Inc.');
INSERT INTO studios (id, name) VALUES (388,'Indeprox');
INSERT INTO studios (id, name) VALUES (389,'Indivision');
INSERT INTO studios (id, name) VALUES (390,'Infinity Vision');
INSERT INTO studios (id, name) VALUES (391,'Inugoya');
INSERT INTO studios (id, name) VALUES (392,'Irawias');
INSERT INTO studios (id, name) VALUES (393,'Ishibashi Planning');
INSERT INTO studios (id, name) VALUES (394,'Ishikawa Pro');
INSERT INTO studios (id, name) VALUES (395,'Ishimori Entertainment');
INSERT INTO studios (id, name) VALUES (396,'Issen');
INSERT INTO studios (id, name) VALUES (397,'Itasca Studio');
INSERT INTO studios (id, name) VALUES (398,'ixtl');
INSERT INTO studios (id, name) VALUES (399,'Iyasakadou Film');
INSERT INTO studios (id, name) VALUES (400,'J.C.F.');
INSERT INTO studios (id, name) VALUES (401,'J.C.Staff');
INSERT INTO studios (id, name) VALUES (402,'J.K.I');
INSERT INTO studios (id, name) VALUES (403,'Japan Taps');
INSERT INTO studios (id, name) VALUES (404,'Japan Vistec');
INSERT INTO studios (id, name) VALUES (405,'JCF');
INSERT INTO studios (id, name) VALUES (406,'Jichitai Anime');
INSERT INTO studios (id, name) VALUES (407,'Jinnan Studio');
INSERT INTO studios (id, name) VALUES (408,'Jinnis Animation Studios');
INSERT INTO studios (id, name) VALUES (409,'JJJOY Animation Studios');
INSERT INTO studios (id, name) VALUES (410,'JM Animation');
INSERT INTO studios (id, name) VALUES (411,'JOF');
INSERT INTO studios (id, name) VALUES (412,'Joicy Studio');
INSERT INTO studios (id, name) VALUES (413,'Joker Films');
INSERT INTO studios (id, name) VALUES (414,'Jumondo');
INSERT INTO studios (id, name) VALUES (415,'Jumonji');
INSERT INTO studios (id, name) VALUES (416,'K-Factory');
INSERT INTO studios (id, name) VALUES (417,'Kaca Entertainment');
INSERT INTO studios (id, name) VALUES (418,'Kachidoki Studio');
INSERT INTO studios (id, name) VALUES (419,'Kaeruotoko Shokai');
INSERT INTO studios (id, name) VALUES (420,'KAGAYA Studio');
INSERT INTO studios (id, name) VALUES (421,'Kami Kukan');
INSERT INTO studios (id, name) VALUES (422,'Kamikaze Douga');
INSERT INTO studios (id, name) VALUES (423,'Kamio Japan');
INSERT INTO studios (id, name) VALUES (424,'Kamitsubaki Studio');
INSERT INTO studios (id, name) VALUES (425,'Kanaban Graphics');
INSERT INTO studios (id, name) VALUES (426,'Kaname Productions');
INSERT INTO studios (id, name) VALUES (427,'Kantou Douga Kai');
INSERT INTO studios (id, name) VALUES (428,'Karaku');
INSERT INTO studios (id, name) VALUES (429,'Karasfilms');
INSERT INTO studios (id, name) VALUES (430,'Kate Arrow');
INSERT INTO studios (id, name) VALUES (431,'Kazami Gakuen Koushiki Douga-bu');
INSERT INTO studios (id, name) VALUES (432,'Kazuki Production');
INSERT INTO studios (id, name) VALUES (433,'Keica');
INSERT INTO studios (id, name) VALUES (434,'Kenji Studio');
INSERT INTO studios (id, name) VALUES (435,'Kent House');
INSERT INTO studios (id, name) VALUES (436,'KeyEast');
INSERT INTO studios (id, name) VALUES (437,'Keyring');
INSERT INTO studios (id, name) VALUES (438,'Khara');
INSERT INTO studios (id, name) VALUES (439,'Kigumi');
INSERT INTO studios (id, name) VALUES (440,'Kinema Citrus');
INSERT INTO studios (id, name) VALUES (441,'Kino Production');
INSERT INTO studios (id, name) VALUES (442,'Kitty Film Mitaka Studio');
INSERT INTO studios (id, name) VALUES (443,'KIZAWA Studio');
INSERT INTO studios (id, name) VALUES (444,'KJJ Animation');
INSERT INTO studios (id, name) VALUES (445,'KKC Animation Production');
INSERT INTO studios (id, name) VALUES (446,'Knack Productions');
INSERT INTO studios (id, name) VALUES (447,'Kokusai Eigasha');
INSERT INTO studios (id, name) VALUES (448,'KOO-KI');
INSERT INTO studios (id, name) VALUES (449,'KSS');
INSERT INTO studios (id, name) VALUES (450,'Kuai Ying Hu Yu');
INSERT INTO studios (id, name) VALUES (451,'Kung Fu Frog Animation');
INSERT INTO studios (id, name) VALUES (452,'Kuri Jikken Manga Kobo');
INSERT INTO studios (id, name) VALUES (453,'Kusama Art');
INSERT INTO studios (id, name) VALUES (454,'Kyoto Animation');
INSERT INTO studios (id, name) VALUES (455,'Kyotoma');
INSERT INTO studios (id, name) VALUES (456,'Kyushu Network Animation');
INSERT INTO studios (id, name) VALUES (457,'l-a-unch・BOX');
INSERT INTO studios (id, name) VALUES (458,'LAN Studio');
INSERT INTO studios (id, name) VALUES (459,'LandQ studios');
INSERT INTO studios (id, name) VALUES (460,'Lapin Track');
INSERT INTO studios (id, name) VALUES (461,'Larx Entertainment');
INSERT INTO studios (id, name) VALUES (462,'Lay-duce');
INSERT INTO studios (id, name) VALUES (463,'LB Commerce');
INSERT INTO studios (id, name) VALUES (464,'Lead');
INSERT INTO studios (id, name) VALUES (465,'Lerche');
INSERT INTO studios (id, name) VALUES (466,'Lesprit');
INSERT INTO studios (id, name) VALUES (467,'LEVELS');
INSERT INTO studios (id, name) VALUES (468,'Liber');
INSERT INTO studios (id, name) VALUES (469,'Liberty Animation Studio');
INSERT INTO studios (id, name) VALUES (470,'LICO');
INSERT INTO studios (id, name) VALUES (471,'Lide');
INSERT INTO studios (id, name) VALUES (472,'LIDENFILMS');
INSERT INTO studios (id, name) VALUES (473,'LIDENFILMS Kyoto Studio');
INSERT INTO studios (id, name) VALUES (474,'LIDENFILMS Osaka Studio');
INSERT INTO studios (id, name) VALUES (475,'Life Work');
INSERT INTO studios (id, name) VALUES (476,'Light Chaser Animation Studios');
INSERT INTO studios (id, name) VALUES (477,'Lilix');
INSERT INTO studios (id, name) VALUES (478,'Lingsanwu Animation');
INSERT INTO studios (id, name) VALUES (479,'Live2D Creative Studio');
INSERT INTO studios (id, name) VALUES (480,'Liyu Culture');
INSERT INTO studios (id, name) VALUES (481,'LMD');
INSERT INTO studios (id, name) VALUES (482,'LX Animation Studio');
INSERT INTO studios (id, name) VALUES (483,'L²Studio');
INSERT INTO studios (id, name) VALUES (484,'M&M');
INSERT INTO studios (id, name) VALUES (485,'M.S.C');
INSERT INTO studios (id, name) VALUES (486,'Maboroshi Koubou');
INSERT INTO studios (id, name) VALUES (487,'Mad Box');
INSERT INTO studios (id, name) VALUES (488,'Madhouse');
INSERT INTO studios (id, name) VALUES (489,'Magia Doraglier');
INSERT INTO studios (id, name) VALUES (490,'Magic Bus');
INSERT INTO studios (id, name) VALUES (491,'Magma Studio');
INSERT INTO studios (id, name) VALUES (492,'Maho Film');
INSERT INTO studios (id, name) VALUES (493,'Majin');
INSERT INTO studios (id, name) VALUES (494,'Makaria');
INSERT INTO studios (id, name) VALUES (495,'Making Animation');
INSERT INTO studios (id, name) VALUES (496,'Manglobe');
INSERT INTO studios (id, name) VALUES (497,'MAPPA');
INSERT INTO studios (id, name) VALUES (498,'Marine Entertainment');
INSERT INTO studios (id, name) VALUES (499,'Maro Studio');
INSERT INTO studios (id, name) VALUES (500,'Marone');
INSERT INTO studios (id, name) VALUES (501,'Marui Group');
INSERT INTO studios (id, name) VALUES (502,'Marvy Jack');
INSERT INTO studios (id, name) VALUES (503,'Marza Animation Planet');
INSERT INTO studios (id, name) VALUES (504,'MASTER LIGHTS');
INSERT INTO studios (id, name) VALUES (505,'MAT');
INSERT INTO studios (id, name) VALUES (506,'Maxilla');
INSERT INTO studios (id, name) VALUES (507,'MB planning');
INSERT INTO studios (id, name) VALUES (508,'Melissa');
INSERT INTO studios (id, name) VALUES (509,'Meltdown');
INSERT INTO studios (id, name) VALUES (510,'Meruhensha');
INSERT INTO studios (id, name) VALUES (511,'MI');
INSERT INTO studios (id, name) VALUES (512,'Mikimoto Production');
INSERT INTO studios (id, name) VALUES (513,'Mili Pictures');
INSERT INTO studios (id, name) VALUES (514,'Milky Cartoon');
INSERT INTO studios (id, name) VALUES (515,'Millepensee');
INSERT INTO studios (id, name) VALUES (516,'Mimoid');
INSERT INTO studios (id, name) VALUES (517,'Minakata Laboratory');
INSERT INTO studios (id, name) VALUES (518,'Minami Machi Bugyousho');
INSERT INTO studios (id, name) VALUES (519,'Mippei Eigeki Kiryuukan');
INSERT INTO studios (id, name) VALUES (520,'Mirai Film');
INSERT INTO studios (id, name) VALUES (521,'Mirai Fusion');
INSERT INTO studios (id, name) VALUES (522,'Miyu Productions');
INSERT INTO studios (id, name) VALUES (523,'MMDGP');
INSERT INTO studios (id, name) VALUES (524,'MMT Technology');
INSERT INTO studios (id, name) VALUES (525,'Mokai Technology');
INSERT INTO studios (id, name) VALUES (526,'MoMo Production');
INSERT INTO studios (id, name) VALUES (527,'Momoi Planning');
INSERT INTO studios (id, name) VALUES (528,'monofilmo');
INSERT INTO studios (id, name) VALUES (529,'Monster''s Egg');
INSERT INTO studios (id, name) VALUES (530,'MontBlanc Pictures');
INSERT INTO studios (id, name) VALUES (531,'MooGoo');
INSERT INTO studios (id, name) VALUES (532,'Mook Animation');
INSERT INTO studios (id, name) VALUES (533,'Mook DLE');
INSERT INTO studios (id, name) VALUES (534,'MORIE Inc.');
INSERT INTO studios (id, name) VALUES (535,'Moss Design Unit');
INSERT INTO studios (id, name) VALUES (536,'Motion Magic');
INSERT INTO studios (id, name) VALUES (537,'Mouse');
INSERT INTO studios (id, name) VALUES (538,'Mousou Senka');
INSERT INTO studios (id, name) VALUES (539,'Movic');
INSERT INTO studios (id, name) VALUES (540,'Mushi Production');
INSERT INTO studios (id, name) VALUES (541,'Myung Films');
INSERT INTO studios (id, name) VALUES (542,'Nakamura Production');
INSERT INTO studios (id, name) VALUES (543,'Namu Animation');
INSERT INTO studios (id, name) VALUES (544,'NANON CREATIVE');
INSERT INTO studios (id, name) VALUES (545,'NAZ');
INSERT INTO studios (id, name) VALUES (546,'Neft Film');
INSERT INTO studios (id, name) VALUES (547,'Nekonigashi Inc.');
INSERT INTO studios (id, name) VALUES (548,'Network Kouenji Studio');
INSERT INTO studios (id, name) VALUES (549,'New Deer');
INSERT INTO studios (id, name) VALUES (550,'New Generation');
INSERT INTO studios (id, name) VALUES (551,'Next Media Animation');
INSERT INTO studios (id, name) VALUES (552,'Nexus');
INSERT INTO studios (id, name) VALUES (553,'NHK');
INSERT INTO studios (id, name) VALUES (554,'NHK Art');
INSERT INTO studios (id, name) VALUES (555,'NHK Enterprises');
INSERT INTO studios (id, name) VALUES (556,'Nice Boat Animation');
INSERT INTO studios (id, name) VALUES (557,'Nihikime no Dozeu');
INSERT INTO studios (id, name) VALUES (558,'Nihon Ad Systems');
INSERT INTO studios (id, name) VALUES (559,'Nippon Animation');
INSERT INTO studios (id, name) VALUES (560,'Nippon Ramayana Film Co.');
INSERT INTO studios (id, name) VALUES (561,'Nomad');
INSERT INTO studios (id, name) VALUES (562,'Noovo');
INSERT INTO studios (id, name) VALUES (563,'Nostalook');
INSERT INTO studios (id, name) VALUES (564,'Nur');
INSERT INTO studios (id, name) VALUES (565,'Nut');
INSERT INTO studios (id, name) VALUES (566,'OB Planning');
INSERT INTO studios (id, name) VALUES (567,'October Media');
INSERT INTO studios (id, name) VALUES (568,'Oddjob');
INSERT INTO studios (id, name) VALUES (569,'Odolttogi');
INSERT INTO studios (id, name) VALUES (570,'Office AO');
INSERT INTO studios (id, name) VALUES (571,'Office DCI');
INSERT INTO studios (id, name) VALUES (572,'Office No. 8');
INSERT INTO studios (id, name) VALUES (573,'Office Nobu');
INSERT INTO studios (id, name) VALUES (574,'Office Take Off');
INSERT INTO studios (id, name) VALUES (575,'Office Takeout');
INSERT INTO studios (id, name) VALUES (576,'Oh! Production');
INSERT INTO studios (id, name) VALUES (577,'Okumaza');
INSERT INTO studios (id, name) VALUES (578,'Okuruto Noboru');
INSERT INTO studios (id, name) VALUES (579,'Olive Studio');
INSERT INTO studios (id, name) VALUES (580,'OLM');
INSERT INTO studios (id, name) VALUES (581,'OLM Digital');
INSERT INTO studios (id, name) VALUES (582,'OLM Team Kato');
INSERT INTO studios (id, name) VALUES (583,'OLM Team Yoshioka');
INSERT INTO studios (id, name) VALUES (584,'Onion Studio');
INSERT INTO studios (id, name) VALUES (585,'Onionskin');
INSERT INTO studios (id, name) VALUES (586,'Opera House');
INSERT INTO studios (id, name) VALUES (587,'ORADA COMPANY');
INSERT INTO studios (id, name) VALUES (588,'Orange');
INSERT INTO studios (id, name) VALUES (589,'Ordet');
INSERT INTO studios (id, name) VALUES (590,'ORENDA');
INSERT INTO studios (id, name) VALUES (591,'Oriental Creative Color');
INSERT INTO studios (id, name) VALUES (592,'Original Dream');
INSERT INTO studios (id, name) VALUES (593,'Original Force');
INSERT INTO studios (id, name) VALUES (594,'Otogi Production');
INSERT INTO studios (id, name) VALUES (595,'OTOIRO');
INSERT INTO studios (id, name) VALUES (596,'Overlap');
INSERT INTO studios (id, name) VALUES (597,'Oxybot');
INSERT INTO studios (id, name) VALUES (598,'Oyster');
INSERT INTO studios (id, name) VALUES (599,'OZ');
INSERT INTO studios (id, name) VALUES (600,'Oz Inc.');
INSERT INTO studios (id, name) VALUES (601,'P core');
INSERT INTO studios (id, name) VALUES (602,'P.A. Works');
INSERT INTO studios (id, name) VALUES (603,'P.I.C.S.');
INSERT INTO studios (id, name) VALUES (604,'Painting Dream');
INSERT INTO studios (id, name) VALUES (605,'Palm Studio');
INSERT INTO studios (id, name) VALUES (606,'Pancake');
INSERT INTO studios (id, name) VALUES (607,'Panda Factory');
INSERT INTO studios (id, name) VALUES (608,'Panmedia');
INSERT INTO studios (id, name) VALUES (609,'Paper Animation');
INSERT INTO studios (id, name) VALUES (610,'Paper Plane Animation Studio');
INSERT INTO studios (id, name) VALUES (611,'Passion Paint Animation');
INSERT INTO studios (id, name) VALUES (612,'Passione');
INSERT INTO studios (id, name) VALUES (613,'Pastel');
INSERT INTO studios (id, name) VALUES (614,'Pb Animation Co. Ltd.');
INSERT INTO studios (id, name) VALUES (615,'Peak Hunt');
INSERT INTO studios (id, name) VALUES (616,'PERIMETRON');
INSERT INTO studios (id, name) VALUES (617,'pH Studio');
INSERT INTO studios (id, name) VALUES (618,'Phoenix Entertainment');
INSERT INTO studios (id, name) VALUES (619,'Picograph');
INSERT INTO studios (id, name) VALUES (620,'Picona');
INSERT INTO studios (id, name) VALUES (621,'Picture Magic');
INSERT INTO studios (id, name) VALUES (622,'Pie in the sky');
INSERT INTO studios (id, name) VALUES (623,'Pierrot');
INSERT INTO studios (id, name) VALUES (624,'Pierrot Plus');
INSERT INTO studios (id, name) VALUES (625,'Piko Studio');
INSERT INTO studios (id, name) VALUES (626,'PINE JAM');
INSERT INTO studios (id, name) VALUES (627,'Pink Cat');
INSERT INTO studios (id, name) VALUES (628,'Piso Studio');
INSERT INTO studios (id, name) VALUES (629,'Planet');
INSERT INTO studios (id, name) VALUES (630,'Planet Cartoon');
INSERT INTO studios (id, name) VALUES (631,'Planet Nemo Animation');
INSERT INTO studios (id, name) VALUES (632,'Platinum Vision');
INSERT INTO studios (id, name) VALUES (633,'Plum');
INSERT INTO studios (id, name) VALUES (634,'Plus Heads');
INSERT INTO studios (id, name) VALUES (635,'Pmats9 studio');
INSERT INTO studios (id, name) VALUES (636,'Point Pictures');
INSERT INTO studios (id, name) VALUES (637,'Pollyanna Graphics');
INSERT INTO studios (id, name) VALUES (638,'Poly Animation');
INSERT INTO studios (id, name) VALUES (639,'Polygon Pictures');
INSERT INTO studios (id, name) VALUES (640,'Poncotan');
INSERT INTO studios (id, name) VALUES (641,'PONOS Corporation');
INSERT INTO studios (id, name) VALUES (642,'Pony Canyon');
INSERT INTO studios (id, name) VALUES (643,'Pops Inc.');
INSERT INTO studios (id, name) VALUES (644,'PoRO');
INSERT INTO studios (id, name) VALUES (645,'Potato House');
INSERT INTO studios (id, name) VALUES (646,'PP Project');
INSERT INTO studios (id, name) VALUES (647,'PPM');
INSERT INTO studios (id, name) VALUES (648,'PRA');
INSERT INTO studios (id, name) VALUES (649,'Primastea');
INSERT INTO studios (id, name) VALUES (650,'PrimeTime');
INSERT INTO studios (id, name) VALUES (651,'Production +h.');
INSERT INTO studios (id, name) VALUES (652,'Production D.M.H');
INSERT INTO studios (id, name) VALUES (653,'production doA');
INSERT INTO studios (id, name) VALUES (654,'Production GoodBook');
INSERT INTO studios (id, name) VALUES (655,'Production I.G');
INSERT INTO studios (id, name) VALUES (656,'Production IMS');
INSERT INTO studios (id, name) VALUES (657,'Production Reed');
INSERT INTO studios (id, name) VALUES (658,'Project No.9');
INSERT INTO studios (id, name) VALUES (659,'Project Team Muu');
INSERT INTO studios (id, name) VALUES (660,'Project Team Sarah');
INSERT INTO studios (id, name) VALUES (661,'Public & Basic');
INSERT INTO studios (id, name) VALUES (662,'Pure Arts');
INSERT INTO studios (id, name) VALUES (663,'Purple Cow Studio Japan');
INSERT INTO studios (id, name) VALUES (664,'Puzzle Animation Studio Limited');
INSERT INTO studios (id, name) VALUES (665,'Qianqi Animation');
INSERT INTO studios (id, name) VALUES (666,'Qingxiang Culture');
INSERT INTO studios (id, name) VALUES (667,'Qiying Animation');
INSERT INTO studios (id, name) VALUES (668,'Qiyuan Yinghua');
INSERT INTO studios (id, name) VALUES (669,'Quad');
INSERT INTO studios (id, name) VALUES (670,'Qualia Animation');
INSERT INTO studios (id, name) VALUES (671,'Qubic Pictures');
INSERT INTO studios (id, name) VALUES (672,'Quebico');
INSERT INTO studios (id, name) VALUES (673,'Queen Bee');
INSERT INTO studios (id, name) VALUES (674,'Quyue Technology');
INSERT INTO studios (id, name) VALUES (675,'Qzil.la');
INSERT INTO studios (id, name) VALUES (676,'Rabbit Gate');
INSERT INTO studios (id, name) VALUES (677,'Rabbit Machine');
INSERT INTO studios (id, name) VALUES (678,'Radix');
INSERT INTO studios (id, name) VALUES (679,'RAMS');
INSERT INTO studios (id, name) VALUES (680,'REALTHING');
INSERT INTO studios (id, name) VALUES (681,'Red Dog Culture House');
INSERT INTO studios (id, name) VALUES (682,'Reiki Eyes Animation');
INSERT INTO studios (id, name) VALUES (683,'Remic');
INSERT INTO studios (id, name) VALUES (684,'Revoroot');
INSERT INTO studios (id, name) VALUES (685,'RG Animation Studios');
INSERT INTO studios (id, name) VALUES (686,'Rikuentai');
INSERT INTO studios (id, name) VALUES (687,'Ripple Film');
INSERT INTO studios (id, name) VALUES (688,'Ripromo');
INSERT INTO studios (id, name) VALUES (689,'Rising Force');
INSERT INTO studios (id, name) VALUES (690,'Robot Communications');
INSERT INTO studios (id, name) VALUES (691,'Rocen');
INSERT INTO studios (id, name) VALUES (692,'Rockwell Eyes');
INSERT INTO studios (id, name) VALUES (693,'Romanov Films');
INSERT INTO studios (id, name) VALUES (694,'Ruo Hong Culture');
INSERT INTO studios (id, name) VALUES (695,'Ryuu M''s');
INSERT INTO studios (id, name) VALUES (696,'Saber Project');
INSERT INTO studios (id, name) VALUES (697,'Saetta');
INSERT INTO studios (id, name) VALUES (698,'Saigo no Shudan');
INSERT INTO studios (id, name) VALUES (699,'Sakura Create');
INSERT INTO studios (id, name) VALUES (700,'SAMG Entertainment');
INSERT INTO studios (id, name) VALUES (701,'Samsara Animation Studio');
INSERT INTO studios (id, name) VALUES (702,'Sanctuary');
INSERT INTO studios (id, name) VALUES (703,'Sankaku');
INSERT INTO studios (id, name) VALUES (704,'Sanrio');
INSERT INTO studios (id, name) VALUES (705,'Sanrio Digital');
INSERT INTO studios (id, name) VALUES (706,'SANZIGEN');
INSERT INTO studios (id, name) VALUES (707,'Satelight');
INSERT INTO studios (id, name) VALUES (708,'SBS TV Production');
INSERT INTO studios (id, name) VALUES (709,'Schoolzone');
INSERT INTO studios (id, name) VALUES (710,'Science SARU');
INSERT INTO studios (id, name) VALUES (711,'Scooter Films');
INSERT INTO studios (id, name) VALUES (712,'Sega Interactive');
INSERT INTO studios (id, name) VALUES (713,'SEK Studios');
INSERT INTO studios (id, name) VALUES (714,'SELFISH');
INSERT INTO studios (id, name) VALUES (715,'Seven');
INSERT INTO studios (id, name) VALUES (716,'Seven Arcs');
INSERT INTO studios (id, name) VALUES (717,'Seven Arcs Pictures');
INSERT INTO studios (id, name) VALUES (718,'Seven Stone Entertainment');
INSERT INTO studios (id, name) VALUES (719,'Shaft');
INSERT INTO studios (id, name) VALUES (720,'Shanghai Animation Film Studio');
INSERT INTO studios (id, name) VALUES (721,'Shanghai Hippo Animation');
INSERT INTO studios (id, name) VALUES (722,'Sharefun Studio');
INSERT INTO studios (id, name) VALUES (723,'Shelty');
INSERT INTO studios (id, name) VALUES (724,'Shengguang Knight Culture');
INSERT INTO studios (id, name) VALUES (725,'Shengying Animation');
INSERT INTO studios (id, name) VALUES (726,'Shenman Entertainment');
INSERT INTO studios (id, name) VALUES (727,'Shimogumi');
INSERT INTO studios (id, name) VALUES (728,'Shin-Ei Animation');
INSERT INTO studios (id, name) VALUES (729,'Shindeban Film');
INSERT INTO studios (id, name) VALUES (730,'Shinjukuza');
INSERT INTO studios (id, name) VALUES (731,'Shinkuukan');
INSERT INTO studios (id, name) VALUES (732,'Shion');
INSERT INTO studios (id, name) VALUES (733,'Shirogumi');
INSERT INTO studios (id, name) VALUES (734,'Shochiku Animation Institute');
INSERT INTO studios (id, name) VALUES (735,'Shogakukan Music & Digital Entertainment');
INSERT INTO studios (id, name) VALUES (736,'Shueisha');
INSERT INTO studios (id, name) VALUES (737,'Shuka');
INSERT INTO studios (id, name) VALUES (738,'Shura');
INSERT INTO studios (id, name) VALUES (739,'SIDO LIMITED');
INSERT INTO studios (id, name) VALUES (740,'Signal.MD');
INSERT INTO studios (id, name) VALUES (741,'SIGNIF');
INSERT INTO studios (id, name) VALUES (742,'Silver');
INSERT INTO studios (id, name) VALUES (743,'SILVER LINK.');
INSERT INTO studios (id, name) VALUES (744,'SJYNEXCUS');
INSERT INTO studios (id, name) VALUES (745,'Slow Studio');
INSERT INTO studios (id, name) VALUES (746,'Soeishinsha');
INSERT INTO studios (id, name) VALUES (747,'Soft Garage');
INSERT INTO studios (id, name) VALUES (748,'Sola Digital Arts');
INSERT INTO studios (id, name) VALUES (749,'Sonsan Kikaku');
INSERT INTO studios (id, name) VALUES (750,'Sotsu');
INSERT INTO studios (id, name) VALUES (751,'Sovat Theater');
INSERT INTO studios (id, name) VALUES (752,'Soyep');
INSERT INTO studios (id, name) VALUES (753,'Space Neko Company');
INSERT INTO studios (id, name) VALUES (754,'Space-X');
INSERT INTO studios (id, name) VALUES (755,'Sparkly Key Animation Studio');
INSERT INTO studios (id, name) VALUES (756,'Sparky Animation');
INSERT INTO studios (id, name) VALUES (757,'SPEED');
INSERT INTO studios (id, name) VALUES (758,'Speed Inc.');
INSERT INTO studios (id, name) VALUES (759,'Spell Bound');
INSERT INTO studios (id, name) VALUES (760,'Spooky graphic');
INSERT INTO studios (id, name) VALUES (761,'Spoon');
INSERT INTO studios (id, name) VALUES (762,'Sprite Animation Studios');
INSERT INTO studios (id, name) VALUES (763,'Square Enix Visual Works');
INSERT INTO studios (id, name) VALUES (764,'Square Pictures');
INSERT INTO studios (id, name) VALUES (765,'Staple Entertainment');
INSERT INTO studios (id, name) VALUES (766,'Starry Cube');
INSERT INTO studios (id, name) VALUES (767,'Steamworks');
INSERT INTO studios (id, name) VALUES (768,'Stereotype');
INSERT INTO studios (id, name) VALUES (769,'Steve N'' Steven');
INSERT INTO studios (id, name) VALUES (770,'Stingray');
INSERT INTO studios (id, name) VALUES (771,'Story Effect');
INSERT INTO studios (id, name) VALUES (772,'StoryRiders Co. Ltd.');
INSERT INTO studios (id, name) VALUES (773,'Strawberry Meets Pictures');
INSERT INTO studios (id, name) VALUES (774,'Studio 1st');
INSERT INTO studios (id, name) VALUES (775,'Studio 3Hz');
INSERT INTO studios (id, name) VALUES (776,'Studio 4°C');
INSERT INTO studios (id, name) VALUES (777,'Studio 88');
INSERT INTO studios (id, name) VALUES (778,'Studio 9 Maiami');
INSERT INTO studios (id, name) VALUES (779,'Studio A-CAT');
INSERT INTO studios (id, name) VALUES (780,'Studio A. Craft');
INSERT INTO studios (id, name) VALUES (781,'Studio Add');
INSERT INTO studios (id, name) VALUES (782,'Studio Animal');
INSERT INTO studios (id, name) VALUES (783,'Studio B&M');
INSERT INTO studios (id, name) VALUES (784,'Studio Bind');
INSERT INTO studios (id, name) VALUES (785,'Studio Binzo');
INSERT INTO studios (id, name) VALUES (786,'Studio Blanc.');
INSERT INTO studios (id, name) VALUES (787,'Studio Bogey');
INSERT INTO studios (id, name) VALUES (788,'Studio Boogie Nights');
INSERT INTO studios (id, name) VALUES (789,'Studio CA');
INSERT INTO studios (id, name) VALUES (790,'Studio Chizu');
INSERT INTO studios (id, name) VALUES (791,'Studio Coa');
INSERT INTO studios (id, name) VALUES (792,'Studio Colorido');
INSERT INTO studios (id, name) VALUES (793,'Studio Comet');
INSERT INTO studios (id, name) VALUES (794,'Studio Core');
INSERT INTO studios (id, name) VALUES (795,'Studio Crocodile');
INSERT INTO studios (id, name) VALUES (796,'Studio D-Volt');
INSERT INTO studios (id, name) VALUES (797,'Studio Dadashow');
INSERT INTO studios (id, name) VALUES (798,'Studio Daisy');
INSERT INTO studios (id, name) VALUES (799,'Studio Deen');
INSERT INTO studios (id, name) VALUES (800,'Studio Dolphin Night');
INSERT INTO studios (id, name) VALUES (801,'Studio DURIAN');
INSERT INTO studios (id, name) VALUES (802,'Studio Egg');
INSERT INTO studios (id, name) VALUES (803,'Studio Elle');
INSERT INTO studios (id, name) VALUES (804,'Studio Eromatick');
INSERT INTO studios (id, name) VALUES (805,'Studio Fantasia');
INSERT INTO studios (id, name) VALUES (806,'Studio Flad');
INSERT INTO studios (id, name) VALUES (807,'Studio Flag');
INSERT INTO studios (id, name) VALUES (808,'Studio Fusion');
INSERT INTO studios (id, name) VALUES (809,'Studio G-1Neo');
INSERT INTO studios (id, name) VALUES (810,'Studio Gadget');
INSERT INTO studios (id, name) VALUES (811,'Studio Gazelle');
INSERT INTO studios (id, name) VALUES (812,'Studio Ghibli');
INSERT INTO studios (id, name) VALUES (813,'Studio Gohan');
INSERT INTO studios (id, name) VALUES (814,'Studio Gokumi');
INSERT INTO studios (id, name) VALUES (815,'Studio GOONEYS');
INSERT INTO studios (id, name) VALUES (816,'Studio Gram');
INSERT INTO studios (id, name) VALUES (817,'Studio Guts');
INSERT INTO studios (id, name) VALUES (818,'Studio Hakk');
INSERT INTO studios (id, name) VALUES (819,'studio hb');
INSERT INTO studios (id, name) VALUES (820,'Studio Hibari');
INSERT INTO studios (id, name) VALUES (821,'Studio Himalaya');
INSERT INTO studios (id, name) VALUES (822,'Studio Hokiboshi');
INSERT INTO studios (id, name) VALUES (823,'Studio HUIT');
INSERT INTO studios (id, name) VALUES (824,'Studio Izena');
INSERT INTO studios (id, name) VALUES (825,'Studio Jam');
INSERT INTO studios (id, name) VALUES (826,'Studio Jemi');
INSERT INTO studios (id, name) VALUES (827,'Studio Jin');
INSERT INTO studios (id, name) VALUES (828,'Studio Junio');
INSERT INTO studios (id, name) VALUES (829,'Studio Kafka');
INSERT INTO studios (id, name) VALUES (830,'Studio Kai');
INSERT INTO studios (id, name) VALUES (831,'Studio Kajino');
INSERT INTO studios (id, name) VALUES (832,'Studio Kelmadick');
INSERT INTO studios (id, name) VALUES (833,'Studio Khronos');
INSERT INTO studios (id, name) VALUES (834,'Studio Kikan');
INSERT INTO studios (id, name) VALUES (835,'Studio Kingyoiro');
INSERT INTO studios (id, name) VALUES (836,'Studio Korumi');
INSERT INTO studios (id, name) VALUES (837,'Studio Kyuuma');
INSERT INTO studios (id, name) VALUES (838,'Studio Lings');
INSERT INTO studios (id, name) VALUES (839,'Studio Live');
INSERT INTO studios (id, name) VALUES (840,'Studio M2');
INSERT INTO studios (id, name) VALUES (841,'Studio March');
INSERT INTO studios (id, name) VALUES (842,'Studio Massket');
INSERT INTO studios (id, name) VALUES (843,'Studio Matomo');
INSERT INTO studios (id, name) VALUES (844,'Studio Matrix');
INSERT INTO studios (id, name) VALUES (845,'Studio Meditation With a Pencil');
INSERT INTO studios (id, name) VALUES (846,'Studio Mir');
INSERT INTO studios (id, name) VALUES (847,'Studio Moriken');
INSERT INTO studios (id, name) VALUES (848,'studio MOTHER');
INSERT INTO studios (id, name) VALUES (849,'studio NAGURI');
INSERT INTO studios (id, name) VALUES (850,'Studio Nanahoshi');
INSERT INTO studios (id, name) VALUES (851,'Studio Nuck');
INSERT INTO studios (id, name) VALUES (852,'Studio OX');
INSERT INTO studios (id, name) VALUES (853,'Studio Palette');
INSERT INTO studios (id, name) VALUES (854,'Studio Pastoral');
INSERT INTO studios (id, name) VALUES (855,'Studio Pivote');
INSERT INTO studios (id, name) VALUES (856,'Studio Ponoc');
INSERT INTO studios (id, name) VALUES (857,'Studio Ppuri');
INSERT INTO studios (id, name) VALUES (858,'Studio Prokion');
INSERT INTO studios (id, name) VALUES (859,'Studio PuYUKAI');
INSERT INTO studios (id, name) VALUES (860,'Studio Ranmaru');
INSERT INTO studios (id, name) VALUES (861,'Studio Rikka');
INSERT INTO studios (id, name) VALUES (862,'Studio Shelter');
INSERT INTO studios (id, name) VALUES (863,'Studio Sign');
INSERT INTO studios (id, name) VALUES (864,'Studio Signal');
INSERT INTO studios (id, name) VALUES (865,'Studio Signpost');
INSERT INTO studios (id, name) VALUES (866,'Studio Sota');
INSERT INTO studios (id, name) VALUES (867,'Studio Soul');
INSERT INTO studios (id, name) VALUES (868,'Studio Take Off');
INSERT INTO studios (id, name) VALUES (869,'Studio Ten');
INSERT INTO studios (id, name) VALUES (870,'Studio Ten Carat');
INSERT INTO studios (id, name) VALUES (871,'Studio Tumble');
INSERT INTO studios (id, name) VALUES (872,'Studio UGOKI');
INSERT INTO studios (id, name) VALUES (873,'Studio Unicorn');
INSERT INTO studios (id, name) VALUES (874,'Studio Vandal');
INSERT INTO studios (id, name) VALUES (875,'Studio VOLN');
INSERT INTO studios (id, name) VALUES (876,'Studio W.Baba');
INSERT INTO studios (id, name) VALUES (877,'Studio Wombat');
INSERT INTO studios (id, name) VALUES (878,'Studio World');
INSERT INTO studios (id, name) VALUES (879,'studio YOG');
INSERT INTO studios (id, name) VALUES (880,'Studio Z5');
INSERT INTO studios (id, name) VALUES (881,'Studio Zero');
INSERT INTO studios (id, name) VALUES (882,'Studio! Cucuri');
INSERT INTO studios (id, name) VALUES (883,'STUDIO6''oN');
INSERT INTO studios (id, name) VALUES (884,'StudioRF Inc.');
INSERT INTO studios (id, name) VALUES (885,'StudioXD');
INSERT INTO studios (id, name) VALUES (886,'Sublimation');
INSERT INTO studios (id, name) VALUES (887,'Success Corp.');
INSERT INTO studios (id, name) VALUES (888,'Sugar Boy');
INSERT INTO studios (id, name) VALUES (889,'Sumomo Film');
INSERT INTO studios (id, name) VALUES (890,'Suna Kouhou');
INSERT INTO studios (id, name) VALUES (891,'Sunflowers');
INSERT INTO studios (id, name) VALUES (892,'Sunny Side Up');
INSERT INTO studios (id, name) VALUES (893,'Sunrise');
INSERT INTO studios (id, name) VALUES (894,'Sunrise Beyond');
INSERT INTO studios (id, name) VALUES (895,'Sunwoo Entertainment');
INSERT INTO studios (id, name) VALUES (896,'Super Brain');
INSERT INTO studios (id, name) VALUES (897,'Super Normal Studio');
INSERT INTO studios (id, name) VALUES (898,'Suspenders');
INSERT INTO studios (id, name) VALUES (899,'Suzuki Mirano');
INSERT INTO studios (id, name) VALUES (900,'Synergy Japan');
INSERT INTO studios (id, name) VALUES (901,'SynergySP');
INSERT INTO studios (id, name) VALUES (902,'T-Rex');
INSERT INTO studios (id, name) VALUES (903,'T.P.O');
INSERT INTO studios (id, name) VALUES (904,'Taikong Works');
INSERT INTO studios (id, name) VALUES (905,'Takahashi Studio');
INSERT INTO studios (id, name) VALUES (906,'Takara Tomy A.R.T.S');
INSERT INTO studios (id, name) VALUES (907,'Tama Production');
INSERT INTO studios (id, name) VALUES (908,'Tamura Shigeru Studio');
INSERT INTO studios (id, name) VALUES (909,'Tanglin Culture');
INSERT INTO studios (id, name) VALUES (910,'TANOsim');
INSERT INTO studios (id, name) VALUES (911,'Taomee');
INSERT INTO studios (id, name) VALUES (912,'Tatsunoko Production');
INSERT INTO studios (id, name) VALUES (913,'TCJ');
INSERT INTO studios (id, name) VALUES (914,'Team TillDawn');
INSERT INTO studios (id, name) VALUES (915,'team Yamahitsuji');
INSERT INTO studios (id, name) VALUES (916,'Team YokkyuFuman');
INSERT INTO studios (id, name) VALUES (917,'teamKG');
INSERT INTO studios (id, name) VALUES (918,'Tear Studio');
INSERT INTO studios (id, name) VALUES (919,'Teatro Nishi Tokyo Studio');
INSERT INTO studios (id, name) VALUES (920,'TEC');
INSERT INTO studios (id, name) VALUES (921,'Tecarat');
INSERT INTO studios (id, name) VALUES (922,'Tele-Cartoon Japan');
INSERT INTO studios (id, name) VALUES (923,'Telecom Animation Film');
INSERT INTO studios (id, name) VALUES (924,'Telescreen');
INSERT INTO studios (id, name) VALUES (925,'Ten Tails Animation');
INSERT INTO studios (id, name) VALUES (926,'Tengu Kobo');
INSERT INTO studios (id, name) VALUES (927,'Tezuka Productions');
INSERT INTO studios (id, name) VALUES (928,'The Answer Studio');
INSERT INTO studios (id, name) VALUES (929,'The Monk Studios');
INSERT INTO studios (id, name) VALUES (930,'The Village of Marchen');
INSERT INTO studios (id, name) VALUES (931,'THINGS.');
INSERT INTO studios (id, name) VALUES (932,'Think Corporation');
INSERT INTO studios (id, name) VALUES (933,'THINKR');
INSERT INTO studios (id, name) VALUES (934,'Three-d');
INSERT INTO studios (id, name) VALUES (935,'Thundray');
INSERT INTO studios (id, name) VALUES (936,'TMS Entertainment');
INSERT INTO studios (id, name) VALUES (937,'TNK');
INSERT INTO studios (id, name) VALUES (938,'TOCSIS');
INSERT INTO studios (id, name) VALUES (939,'Toei Animation');
INSERT INTO studios (id, name) VALUES (940,'Toei Video');
INSERT INTO studios (id, name) VALUES (941,'TOHO animation');
INSERT INTO studios (id, name) VALUES (942,'TOHO animation STUDIO');
INSERT INTO studios (id, name) VALUES (943,'Toho Interactive Animation');
INSERT INTO studios (id, name) VALUES (944,'Tokyo Kids');
INSERT INTO studios (id, name) VALUES (945,'Tokyo Media Connections');
INSERT INTO studios (id, name) VALUES (946,'Tokyo Movie');
INSERT INTO studios (id, name) VALUES (947,'Tokyo Movie Shinsha');
INSERT INTO studios (id, name) VALUES (948,'Tomason');
INSERT INTO studios (id, name) VALUES (949,'Tomovies');
INSERT INTO studios (id, name) VALUES (950,'Tomoyasu Murata Company');
INSERT INTO studios (id, name) VALUES (951,'Tonari Animation');
INSERT INTO studios (id, name) VALUES (952,'Tong Ming Xuan');
INSERT INTO studios (id, name) VALUES (953,'Tonko House');
INSERT INTO studios (id, name) VALUES (954,'Topcraft');
INSERT INTO studios (id, name) VALUES (955,'Trans Arts');
INSERT INTO studios (id, name) VALUES (956,'Transcendence Picture');
INSERT INTO studios (id, name) VALUES (957,'Trash Studio');
INSERT INTO studios (id, name) VALUES (958,'trenova');
INSERT INTO studios (id, name) VALUES (959,'Tri-Slash');
INSERT INTO studios (id, name) VALUES (960,'Triangle Staff');
INSERT INTO studios (id, name) VALUES (961,'TriF Studio');
INSERT INTO studios (id, name) VALUES (962,'Trigger');
INSERT INTO studios (id, name) VALUES (963,'Trinet Entertainment');
INSERT INTO studios (id, name) VALUES (964,'TrioPen Studio');
INSERT INTO studios (id, name) VALUES (965,'Triple X');
INSERT INTO studios (id, name) VALUES (966,'TROYCA');
INSERT INTO studios (id, name) VALUES (967,'Tryforce');
INSERT INTO studios (id, name) VALUES (968,'Tsubo Production');
INSERT INTO studios (id, name) VALUES (969,'Tsuburaya Productions');
INSERT INTO studios (id, name) VALUES (970,'Tsuchida Productions');
INSERT INTO studios (id, name) VALUES (971,'Tsukimidou');
INSERT INTO studios (id, name) VALUES (972,'Tsumugi Akita Animation Lab');
INSERT INTO studios (id, name) VALUES (973,'TthunDer Animation');
INSERT INTO studios (id, name) VALUES (974,'TUBA');
INSERT INTO studios (id, name) VALUES (975,'Twenty First');
INSERT INTO studios (id, name) VALUES (976,'Twilight Studio');
INSERT INTO studios (id, name) VALUES (977,'Twilight Town');
INSERT INTO studios (id, name) VALUES (978,'Twin Engine');
INSERT INTO studios (id, name) VALUES (979,'TYMOTE');
INSERT INTO studios (id, name) VALUES (980,'TYO Animations');
INSERT INTO studios (id, name) VALUES (981,'TypeZero');
INSERT INTO studios (id, name) VALUES (982,'Typhoon Graphics');
INSERT INTO studios (id, name) VALUES (983,'UchuPeople');
INSERT INTO studios (id, name) VALUES (984,'ufotable');
INSERT INTO studios (id, name) VALUES (985,'Uguisu Kobo');
INSERT INTO studios (id, name) VALUES (986,'Ultra Super Pictures');
INSERT INTO studios (id, name) VALUES (987,'Unend');
INSERT INTO studios (id, name) VALUES (988,'UNKNOWN');
INSERT INTO studios (id, name) VALUES (989,'Urban Product');
INSERT INTO studios (id, name) VALUES (990,'Usagi Ou');
INSERT INTO studios (id, name) VALUES (991,'UWAN Pictures');
INSERT INTO studios (id, name) VALUES (992,'V-sign');
INSERT INTO studios (id, name) VALUES (993,'Vasoon Animation');
INSERT INTO studios (id, name) VALUES (994,'VCRWORKS');
INSERT INTO studios (id, name) VALUES (995,'Vega Entertainment');
INSERT INTO studios (id, name) VALUES (996,'Venet');
INSERT INTO studios (id, name) VALUES (997,'View Works');
INSERT INTO studios (id, name) VALUES (998,'Visual 80');
INSERT INTO studios (id, name) VALUES (999,'Visual Flight');
INSERT INTO studios (id, name) VALUES (1000,'Voil');
INSERT INTO studios (id, name) VALUES (1001,'W+K Tokyo');
INSERT INTO studios (id, name) VALUES (1002,'W-Toon Studio');
INSERT INTO studios (id, name) VALUES (1003,'Wako Productions');
INSERT INTO studios (id, name) VALUES (1004,'WAO World');
INSERT INTO studios (id, name) VALUES (1005,'Wawayu Animation');
INSERT INTO studios (id, name) VALUES (1006,'Wei Chuang Jiang Xin');
INSERT INTO studios (id, name) VALUES (1007,'Welz Animation Studios');
INSERT INTO studios (id, name) VALUES (1008,'White Fox');
INSERT INTO studios (id, name) VALUES (1009,'WHOPPERS');
INSERT INTO studios (id, name) VALUES (1010,'Will Palette');
INSERT INTO studios (id, name) VALUES (1011,'Wise Guy');
INSERT INTO studios (id, name) VALUES (1012,'Wit Studio');
INSERT INTO studios (id, name) VALUES (1013,'Wolf Smoke Studio');
INSERT INTO studios (id, name) VALUES (1014,'Wolfsbane');
INSERT INTO studios (id, name) VALUES (1015,'Wonder Cat Animation');
INSERT INTO studios (id, name) VALUES (1016,'Wong Ping Animation Lab');
INSERT INTO studios (id, name) VALUES (1017,'Wulifang Digital');
INSERT INTO studios (id, name) VALUES (1018,'Xanthus Media');
INSERT INTO studios (id, name) VALUES (1019,'Xebec');
INSERT INTO studios (id, name) VALUES (1020,'XEBEC M2');
INSERT INTO studios (id, name) VALUES (1021,'XFLAG');
INSERT INTO studios (id, name) VALUES (1022,'XFLAG Pictures');
INSERT INTO studios (id, name) VALUES (1023,'Xing Yi Kai Chen');
INSERT INTO studios (id, name) VALUES (1024,'Xuni Ying Ye');
INSERT INTO studios (id, name) VALUES (1025,'Y.O.U.C');
INSERT INTO studios (id, name) VALUES (1026,'Yamamura Animation');
INSERT INTO studios (id, name) VALUES (1027,'Yamato Works');
INSERT INTO studios (id, name) VALUES (1028,'Yamiken');
INSERT INTO studios (id, name) VALUES (1029,'Yaoyorozu');
INSERT INTO studios (id, name) VALUES (1030,'yell');
INSERT INTO studios (id, name) VALUES (1031,'YHKT Entertainment');
INSERT INTO studios (id, name) VALUES (1032,'Yi Chen Animation');
INSERT INTO studios (id, name) VALUES (1033,'Yinhe Changxing Culture');
INSERT INTO studios (id, name) VALUES (1034,'Yokohama Animation Lab');
INSERT INTO studios (id, name) VALUES (1035,'Yonago Gainax');
INSERT INTO studios (id, name) VALUES (1036,'Yostar Pictures');
INSERT INTO studios (id, name) VALUES (1037,'Youku');
INSERT INTO studios (id, name) VALUES (1038,'Yuhodo');
INSERT INTO studios (id, name) VALUES (1039,'Yumeta Company');
INSERT INTO studios (id, name) VALUES (1040,'YURUPPE Inc.');
INSERT INTO studios (id, name) VALUES (1041,'Zero-G');
INSERT INTO studios (id, name) VALUES (1042,'Zero-G Room');
INSERT INTO studios (id, name) VALUES (1043,'Zexcs');
INSERT INTO studios (id, name) VALUES (1044,'Zyc');

-- migrate:down 

DELETE FROM studios;