--migrate:up 

INSERT INTO licensors (id, name) VALUES (1,'4Kids Entertainment');
INSERT INTO licensors (id, name) VALUES (2,'ADK Emotions NY');
INSERT INTO licensors (id, name) VALUES (3,'Adult Source Media');
INSERT INTO licensors (id, name) VALUES (4,'ADV Films');
INSERT INTO licensors (id, name) VALUES (5,'AN Entertainment');
INSERT INTO licensors (id, name) VALUES (6,'Anchor Bay Films');
INSERT INTO licensors (id, name) VALUES (7,'Anime Midstream');
INSERT INTO licensors (id, name) VALUES (8,'AnimEigo');
INSERT INTO licensors (id, name) VALUES (9,'Aniplex of America');
INSERT INTO licensors (id, name) VALUES (10,'Arts Magic');
INSERT INTO licensors (id, name) VALUES (11,'Ascendent Animation');
INSERT INTO licensors (id, name) VALUES (12,'B.CMAY PICTURES');
INSERT INTO licensors (id, name) VALUES (13,'Bandai');
INSERT INTO licensors (id, name) VALUES (14,'Bandai Entertainment');
INSERT INTO licensors (id, name) VALUES (15,'Bandai Namco Games');
INSERT INTO licensors (id, name) VALUES (16,'Bandai Namco Online');
INSERT INTO licensors (id, name) VALUES (17,'Bandai Visual USA');
INSERT INTO licensors (id, name) VALUES (18,'bilibili');
INSERT INTO licensors (id, name) VALUES (19,'Capcom');
INSERT INTO licensors (id, name) VALUES (20,'Central Park Media');
INSERT INTO licensors (id, name) VALUES (21,'Cinelicious Pics');
INSERT INTO licensors (id, name) VALUES (22,'Cookie Jar Entertainment');
INSERT INTO licensors (id, name) VALUES (23,'Crimson Star Media');
INSERT INTO licensors (id, name) VALUES (24,'Critical Mass Video');
INSERT INTO licensors (id, name) VALUES (25,'Crunchyroll');
INSERT INTO licensors (id, name) VALUES (26,'Dentsu Entertainment USA');
INSERT INTO licensors (id, name) VALUES (27,'DiC Entertainment');
INSERT INTO licensors (id, name) VALUES (28,'Directions');
INSERT INTO licensors (id, name) VALUES (29,'Discotek Media');
INSERT INTO licensors (id, name) VALUES (30,'Disney Platform Distribution');
INSERT INTO licensors (id, name) VALUES (31,'DreamWorks');
INSERT INTO licensors (id, name) VALUES (32,'Eleven Arts');
INSERT INTO licensors (id, name) VALUES (33,'Enoki Films');
INSERT INTO licensors (id, name) VALUES (34,'Flatiron Film Company');
INSERT INTO licensors (id, name) VALUES (35,'Frontier Works');
INSERT INTO licensors (id, name) VALUES (36,'Funimation');
INSERT INTO licensors (id, name) VALUES (37,'Geneon Entertainment USA');
INSERT INTO licensors (id, name) VALUES (38,'Geneon Universal Entertainment');
INSERT INTO licensors (id, name) VALUES (39,'GKIDS');
INSERT INTO licensors (id, name) VALUES (40,'Haoliners Animation League');
INSERT INTO licensors (id, name) VALUES (41,'Harmony Gold');
INSERT INTO licensors (id, name) VALUES (42,'Hasbro');
INSERT INTO licensors (id, name) VALUES (43,'Hirameki International');
INSERT INTO licensors (id, name) VALUES (44,'Illumitoon Entertainment');
INSERT INTO licensors (id, name) VALUES (45,'Inc.');
INSERT INTO licensors (id, name) VALUES (46,'iQIYI');
INSERT INTO licensors (id, name) VALUES (47,'JapanAnime');
INSERT INTO licensors (id, name) VALUES (48,'Kadokawa');
INSERT INTO licensors (id, name) VALUES (49,'Kadokawa Pictures USA');
INSERT INTO licensors (id, name) VALUES (50,'Ketchup Entertainment');
INSERT INTO licensors (id, name) VALUES (51,'Kitty Media');
INSERT INTO licensors (id, name) VALUES (52,'Konami Cross Media NY');
INSERT INTO licensors (id, name) VALUES (53,'Kuma Holdings');
INSERT INTO licensors (id, name) VALUES (54,'Maiden Japan');
INSERT INTO licensors (id, name) VALUES (55,'Manga Entertainment');
INSERT INTO licensors (id, name) VALUES (56,'Marvel Entertainment');
INSERT INTO licensors (id, name) VALUES (57,'Media Blasters');
INSERT INTO licensors (id, name) VALUES (58,'Mill Creek Entertainment');
INSERT INTO licensors (id, name) VALUES (59,'Miramax Films');
INSERT INTO licensors (id, name) VALUES (60,'Muse Communication');
INSERT INTO licensors (id, name) VALUES (61,'NBCUniversal Entertainment Japan');
INSERT INTO licensors (id, name) VALUES (62,'Nelvana');
INSERT INTO licensors (id, name) VALUES (63,'Nintendo of America');
INSERT INTO licensors (id, name) VALUES (64,'NIS America');
INSERT INTO licensors (id, name) VALUES (65,'Nozomi Entertainment');
INSERT INTO licensors (id, name) VALUES (66,'NuTech Digital');
INSERT INTO licensors (id, name) VALUES (67,'NYAV Post');
INSERT INTO licensors (id, name) VALUES (68,'Pied Piper');
INSERT INTO licensors (id, name) VALUES (69,'Pioneer LDC');
INSERT INTO licensors (id, name) VALUES (70,'Ponycan USA');
INSERT INTO licensors (id, name) VALUES (71,'Saban Brands');
INSERT INTO licensors (id, name) VALUES (72,'Saban Entertainment');
INSERT INTO licensors (id, name) VALUES (73,'Sentai Filmworks');
INSERT INTO licensors (id, name) VALUES (74,'Shout! Factory');
INSERT INTO licensors (id, name) VALUES (75,'SoftCel Pictures');
INSERT INTO licensors (id, name) VALUES (76,'Sony Pictures Entertainment');
INSERT INTO licensors (id, name) VALUES (77,'Sony Pictures Worldwide Acquisitions');
INSERT INTO licensors (id, name) VALUES (78,'Streamline Pictures');
INSERT INTO licensors (id, name) VALUES (79,'Super Techno Arts');
INSERT INTO licensors (id, name) VALUES (80,'Synch-Point');
INSERT INTO licensors (id, name) VALUES (81,'The Pokemon Company International');
INSERT INTO licensors (id, name) VALUES (82,'Tokyopop');
INSERT INTO licensors (id, name) VALUES (83,'Travel Compass');
INSERT INTO licensors (id, name) VALUES (84,'UNKNOWN');
INSERT INTO licensors (id, name) VALUES (85,'Urban Vision');
INSERT INTO licensors (id, name) VALUES (86,'VIZ Media');
INSERT INTO licensors (id, name) VALUES (87,'Voyager Entertainment');
INSERT INTO licensors (id, name) VALUES (88,'Warner Bros. Pictures');

-- migrate:down 

DELETE FROM licensors;