--migrate:up 

INSERT INTO producers (id, name) VALUES (1,'100studio');
INSERT INTO producers (id, name) VALUES (2,'10Gauge');
INSERT INTO producers (id, name) VALUES (3,'12 Diary Holders');
INSERT INTO producers (id, name) VALUES (4,'1IN');
INSERT INTO producers (id, name) VALUES (5,'1st PLACE');
INSERT INTO producers (id, name) VALUES (6,'1theK');
INSERT INTO producers (id, name) VALUES (7,'2:10 AM Animation');
INSERT INTO producers (id, name) VALUES (8,'3xCube');
INSERT INTO producers (id, name) VALUES (9,'4Kids Entertainment');
INSERT INTO producers (id, name) VALUES (10,'5pb.');
INSERT INTO producers (id, name) VALUES (11,'7ji');
INSERT INTO producers (id, name) VALUES (12,'81 Produce');
INSERT INTO producers (id, name) VALUES (13,'8PAN');
INSERT INTO producers (id, name) VALUES (14,'A-1 Pictures');
INSERT INTO producers (id, name) VALUES (15,'A-Craft');
INSERT INTO producers (id, name) VALUES (16,'A-Line');
INSERT INTO producers (id, name) VALUES (17,'A-Sketch');
INSERT INTO producers (id, name) VALUES (18,'A3');
INSERT INTO producers (id, name) VALUES (19,'ABC Animation');
INSERT INTO producers (id, name) VALUES (20,'ABC Frontier');
INSERT INTO producers (id, name) VALUES (21,'Abe Shuuji Jimusho');
INSERT INTO producers (id, name) VALUES (22,'AbemaTV');
INSERT INTO producers (id, name) VALUES (23,'AC Create');
INSERT INTO producers (id, name) VALUES (24,'AC-Bu');
INSERT INTO producers (id, name) VALUES (25,'Academy Productions');
INSERT INTO producers (id, name) VALUES (26,'Ace Crew Entertainment');
INSERT INTO producers (id, name) VALUES (27,'Actas');
INSERT INTO producers (id, name) VALUES (28,'Active');
INSERT INTO producers (id, name) VALUES (29,'Adda Audio Visual Ltd.');
INSERT INTO producers (id, name) VALUES (30,'ADK');
INSERT INTO producers (id, name) VALUES (31,'ADK Emotions');
INSERT INTO producers (id, name) VALUES (32,'ADK Marketing Solutions');
INSERT INTO producers (id, name) VALUES (33,'Adores');
INSERT INTO producers (id, name) VALUES (34,'Adult Source Media');
INSERT INTO producers (id, name) VALUES (35,'Advance Syakujii');
INSERT INTO producers (id, name) VALUES (36,'Aeon Entertainment');
INSERT INTO producers (id, name) VALUES (37,'AG-ONE');
INSERT INTO producers (id, name) VALUES (38,'Age');
INSERT INTO producers (id, name) VALUES (39,'Age Global Networks');
INSERT INTO producers (id, name) VALUES (40,'Agent 21');
INSERT INTO producers (id, name) VALUES (41,'AHA Entertainment');
INSERT INTO producers (id, name) VALUES (42,'Ai Addiction');
INSERT INTO producers (id, name) VALUES (43,'Ai ga areba Daijobu');
INSERT INTO producers (id, name) VALUES (44,'AIC');
INSERT INTO producers (id, name) VALUES (45,'AIC RIGHTS');
INSERT INTO producers (id, name) VALUES (46,'Aikikaku Center');
INSERT INTO producers (id, name) VALUES (47,'Aiming');
INSERT INTO producers (id, name) VALUES (48,'AIR AGENCY');
INSERT INTO producers (id, name) VALUES (49,'Ajia-do');
INSERT INTO producers (id, name) VALUES (50,'Akabanten');
INSERT INTO producers (id, name) VALUES (51,'AKABEiSOFT2');
INSERT INTO producers (id, name) VALUES (52,'Akatsuki');
INSERT INTO producers (id, name) VALUES (53,'Akita Shoten');
INSERT INTO producers (id, name) VALUES (54,'Alchemist');
INSERT INTO producers (id, name) VALUES (55,'Alchemy Bros.');
INSERT INTO producers (id, name) VALUES (56,'Alibaba Pictures');
INSERT INTO producers (id, name) VALUES (57,'Alice');
INSERT INTO producers (id, name) VALUES (58,'All Products');
INSERT INTO producers (id, name) VALUES (59,'Allure');
INSERT INTO producers (id, name) VALUES (60,'Alpha Animation');
INSERT INTO producers (id, name) VALUES (61,'Alpha Group Co. Ltd.');
INSERT INTO producers (id, name) VALUES (62,'Alpha Pictures');
INSERT INTO producers (id, name) VALUES (63,'AlphaPolis');
INSERT INTO producers (id, name) VALUES (64,'Amber Film Works');
INSERT INTO producers (id, name) VALUES (65,'AMG Entertainment');
INSERT INTO producers (id, name) VALUES (66,'AMG MUSIC');
INSERT INTO producers (id, name) VALUES (67,'Amino');
INSERT INTO producers (id, name) VALUES (68,'Amumo');
INSERT INTO producers (id, name) VALUES (69,'Amuse');
INSERT INTO producers (id, name) VALUES (70,'Amuse Pictures');
INSERT INTO producers (id, name) VALUES (71,'Amusement Media Academy');
INSERT INTO producers (id, name) VALUES (72,'Anchor');
INSERT INTO producers (id, name) VALUES (73,'Angelfish');
INSERT INTO producers (id, name) VALUES (74,'Anhui Xinhua Media');
INSERT INTO producers (id, name) VALUES (75,'ANIK');
INSERT INTO producers (id, name) VALUES (76,'Anima&Co.');
INSERT INTO producers (id, name) VALUES (77,'Animac');
INSERT INTO producers (id, name) VALUES (78,'AniMan');
INSERT INTO producers (id, name) VALUES (79,'Animaruya');
INSERT INTO producers (id, name) VALUES (80,'animate');
INSERT INTO producers (id, name) VALUES (81,'animate Film');
INSERT INTO producers (id, name) VALUES (82,'Animatic');
INSERT INTO producers (id, name) VALUES (83,'Animation Do');
INSERT INTO producers (id, name) VALUES (84,'Animatsu Entertainment');
INSERT INTO producers (id, name) VALUES (85,'Animax');
INSERT INTO producers (id, name) VALUES (86,'Anime Antenna Iinkai');
INSERT INTO producers (id, name) VALUES (87,'Anime Beans');
INSERT INTO producers (id, name) VALUES (88,'Anime Consortium Japan');
INSERT INTO producers (id, name) VALUES (89,'Anime Friend');
INSERT INTO producers (id, name) VALUES (90,'Anime R');
INSERT INTO producers (id, name) VALUES (91,'ANiMix Project');
INSERT INTO producers (id, name) VALUES (92,'Aniplex');
INSERT INTO producers (id, name) VALUES (93,'Ankama');
INSERT INTO producers (id, name) VALUES (94,'Annapuru');
INSERT INTO producers (id, name) VALUES (95,'Antechinus');
INSERT INTO producers (id, name) VALUES (96,'Aoi Studio');
INSERT INTO producers (id, name) VALUES (97,'AOMG');
INSERT INTO producers (id, name) VALUES (98,'Aoni Entertainment');
INSERT INTO producers (id, name) VALUES (99,'Aoni Production');
INSERT INTO producers (id, name) VALUES (100,'APDREAM');
INSERT INTO producers (id, name) VALUES (101,'Apollon');
INSERT INTO producers (id, name) VALUES (102,'APPP');
INSERT INTO producers (id, name) VALUES (103,'AQUA ARIS');
INSERT INTO producers (id, name) VALUES (104,'Aquamarine');
INSERT INTO producers (id, name) VALUES (105,'AQUAPLUS');
INSERT INTO producers (id, name) VALUES (106,'Arc Studio');
INSERT INTO producers (id, name) VALUES (107,'Arch');
INSERT INTO producers (id, name) VALUES (108,'Arcturus');
INSERT INTO producers (id, name) VALUES (109,'arma bianca');
INSERT INTO producers (id, name) VALUES (110,'Armor');
INSERT INTO producers (id, name) VALUES (111,'Arms');
INSERT INTO producers (id, name) VALUES (112,'Arplants');
INSERT INTO producers (id, name) VALUES (113,'Arquebuse');
INSERT INTO producers (id, name) VALUES (114,'Artist Management Office');
INSERT INTO producers (id, name) VALUES (115,'Artland');
INSERT INTO producers (id, name) VALUES (116,'Artmic');
INSERT INTO producers (id, name) VALUES (117,'Arts Magic');
INSERT INTO producers (id, name) VALUES (118,'Asahi Broadcasting');
INSERT INTO producers (id, name) VALUES (119,'Asahi Production');
INSERT INTO producers (id, name) VALUES (120,'Asahi Shimbun');
INSERT INTO producers (id, name) VALUES (121,'Asahi Shinbun Shuppan');
INSERT INTO producers (id, name) VALUES (122,'Asatsu DK');
INSERT INTO producers (id, name) VALUES (123,'ASCII Media Works');
INSERT INTO producers (id, name) VALUES (124,'Asgard');
INSERT INTO producers (id, name) VALUES (125,'Ashi Productions');
INSERT INTO producers (id, name) VALUES (126,'Ashisuto');
INSERT INTO producers (id, name) VALUES (127,'ASIA Documentary Productions');
INSERT INTO producers (id, name) VALUES (128,'ASK Animation Studio');
INSERT INTO producers (id, name) VALUES (129,'Asmik Ace');
INSERT INTO producers (id, name) VALUES (130,'Assez Finaud Fabric');
INSERT INTO producers (id, name) VALUES (131,'Asura Film');
INSERT INTO producers (id, name) VALUES (132,'AT-X');
INSERT INTO producers (id, name) VALUES (133,'Atelier Musa');
INSERT INTO producers (id, name) VALUES (134,'Atlus');
INSERT INTO producers (id, name) VALUES (135,'Aubec');
INSERT INTO producers (id, name) VALUES (136,'Audio Graphics Institute');
INSERT INTO producers (id, name) VALUES (137,'Audio Highs');
INSERT INTO producers (id, name) VALUES (138,'Audio Planning U');
INSERT INTO producers (id, name) VALUES (139,'Audio Tanaka');
INSERT INTO producers (id, name) VALUES (140,'Avaco Creative Studios');
INSERT INTO producers (id, name) VALUES (141,'Avex Entertainment');
INSERT INTO producers (id, name) VALUES (142,'Avex Pictures');
INSERT INTO producers (id, name) VALUES (143,'Avex Technologies');
INSERT INTO producers (id, name) VALUES (144,'AYCO');
INSERT INTO producers (id, name) VALUES (145,'AZ Creative');
INSERT INTO producers (id, name) VALUES (146,'Azeta Pictures');
INSERT INTO producers (id, name) VALUES (147,'Azumaker');
INSERT INTO producers (id, name) VALUES (148,'B.CMAY PICTURES');
INSERT INTO producers (id, name) VALUES (149,'Baku Enterprise');
INSERT INTO producers (id, name) VALUES (150,'Bandai');
INSERT INTO producers (id, name) VALUES (151,'Bandai Channel');
INSERT INTO producers (id, name) VALUES (152,'Bandai Namco Arts');
INSERT INTO producers (id, name) VALUES (153,'Bandai Namco Entertainment');
INSERT INTO producers (id, name) VALUES (154,'Bandai Namco Filmworks');
INSERT INTO producers (id, name) VALUES (155,'Bandai Namco Games');
INSERT INTO producers (id, name) VALUES (156,'Bandai Namco Live Creative');
INSERT INTO producers (id, name) VALUES (157,'Bandai Namco Music Live');
INSERT INTO producers (id, name) VALUES (158,'Bandai Namco Online');
INSERT INTO producers (id, name) VALUES (159,'Bandai Namco Pictures');
INSERT INTO producers (id, name) VALUES (160,'Bandai Namco Rights Marketing');
INSERT INTO producers (id, name) VALUES (161,'Bandai Spirits');
INSERT INTO producers (id, name) VALUES (162,'Bandai Visual');
INSERT INTO producers (id, name) VALUES (163,'Banpresto');
INSERT INTO producers (id, name) VALUES (164,'Baramiri');
INSERT INTO producers (id, name) VALUES (165,'Barnum Studio');
INSERT INTO producers (id, name) VALUES (166,'BEAM Entertainment');
INSERT INTO producers (id, name) VALUES (167,'Bebow');
INSERT INTO producers (id, name) VALUES (168,'BeDream');
INSERT INTO producers (id, name) VALUES (169,'Bee Media');
INSERT INTO producers (id, name) VALUES (170,'Bee Train');
INSERT INTO producers (id, name) VALUES (171,'BeeWorks');
INSERT INTO producers (id, name) VALUES (172,'Beijing Enlight Pictures');
INSERT INTO producers (id, name) VALUES (173,'Beijing IMMG');
INSERT INTO producers (id, name) VALUES (174,'Beijing Sharaku Art');
INSERT INTO producers (id, name) VALUES (175,'Beijing Sunchime Happy Culture Company');
INSERT INTO producers (id, name) VALUES (176,'Being');
INSERT INTO producers (id, name) VALUES (177,'Benesse Corporation');
INSERT INTO producers (id, name) VALUES (178,'Bergamo');
INSERT INTO producers (id, name) VALUES (179,'BeSTACK');
INSERT INTO producers (id, name) VALUES (180,'Beyond C.');
INSERT INTO producers (id, name) VALUES (181,'Bibury Animation CG');
INSERT INTO producers (id, name) VALUES (182,'Bic Studio');
INSERT INTO producers (id, name) VALUES (183,'Big Bang');
INSERT INTO producers (id, name) VALUES (184,'Big Film Entertainment');
INSERT INTO producers (id, name) VALUES (185,'Big West');
INSERT INTO producers (id, name) VALUES (186,'BIGFACE');
INSERT INTO producers (id, name) VALUES (187,'BIGLOBE');
INSERT INTO producers (id, name) VALUES (188,'bilibili');
INSERT INTO producers (id, name) VALUES (189,'Bishop');
INSERT INTO producers (id, name) VALUES (190,'Bit grooove promotion');
INSERT INTO producers (id, name) VALUES (191,'Bit Promotion');
INSERT INTO producers (id, name) VALUES (192,'Bitgang');
INSERT INTO producers (id, name) VALUES (193,'blackflag');
INSERT INTO producers (id, name) VALUES (194,'Blade');
INSERT INTO producers (id, name) VALUES (195,'Bliss Pictures');
INSERT INTO producers (id, name) VALUES (196,'BloomZ');
INSERT INTO producers (id, name) VALUES (197,'Blue Eyes');
INSERT INTO producers (id, name) VALUES (198,'Blue Lynx');
INSERT INTO producers (id, name) VALUES (199,'Blue Moon Studio Inc.');
INSERT INTO producers (id, name) VALUES (200,'BMG Japan');
INSERT INTO producers (id, name) VALUES (201,'BOMB! CUTE! BOMB!');
INSERT INTO producers (id, name) VALUES (202,'Bones');
INSERT INTO producers (id, name) VALUES (203,'BookLive');
INSERT INTO producers (id, name) VALUES (204,'BOOTLEG');
INSERT INTO producers (id, name) VALUES (205,'Bouncy');
INSERT INTO producers (id, name) VALUES (206,'Boyan Pictures');
INSERT INTO producers (id, name) VALUES (207,'Brain''s Base');
INSERT INTO producers (id, name) VALUES (208,'Brave group');
INSERT INTO producers (id, name) VALUES (209,'Brave Hearts');
INSERT INTO producers (id, name) VALUES (210,'BreakBottle');
INSERT INTO producers (id, name) VALUES (211,'Bridge');
INSERT INTO producers (id, name) VALUES (212,'Broccoli');
INSERT INTO producers (id, name) VALUES (213,'BS Asahi');
INSERT INTO producers (id, name) VALUES (214,'BS Fuji');
INSERT INTO producers (id, name) VALUES (215,'BS Japan');
INSERT INTO producers (id, name) VALUES (216,'BS NTV');
INSERT INTO producers (id, name) VALUES (217,'BS-i');
INSERT INTO producers (id, name) VALUES (218,'BS-TBS');
INSERT INTO producers (id, name) VALUES (219,'BS11');
INSERT INTO producers (id, name) VALUES (220,'Bulls Eye');
INSERT INTO producers (id, name) VALUES (221,'Bungeishunjuu');
INSERT INTO producers (id, name) VALUES (222,'Bushiroad');
INSERT INTO producers (id, name) VALUES (223,'Bushiroad Creative');
INSERT INTO producers (id, name) VALUES (224,'Bushiroad Move');
INSERT INTO producers (id, name) VALUES (225,'Bushiroad Music');
INSERT INTO producers (id, name) VALUES (226,'Buzz Wave');
INSERT INTO producers (id, name) VALUES (227,'Byakuya Shobo');
INSERT INTO producers (id, name) VALUES (228,'Bytehoo');
INSERT INTO producers (id, name) VALUES (229,'C & I entertainment');
INSERT INTO producers (id, name) VALUES (230,'C-one');
INSERT INTO producers (id, name) VALUES (231,'C2C');
INSERT INTO producers (id, name) VALUES (232,'CA-Cygames Anime Fund');
INSERT INTO producers (id, name) VALUES (233,'Calf Studio');
INSERT INTO producers (id, name) VALUES (234,'Cammot');
INSERT INTO producers (id, name) VALUES (235,'Capcom');
INSERT INTO producers (id, name) VALUES (236,'Carp Studio');
INSERT INTO producers (id, name) VALUES (237,'CaRTe bLaNChe');
INSERT INTO producers (id, name) VALUES (238,'Casio Entertainment');
INSERT INTO producers (id, name) VALUES (239,'CBC Television');
INSERT INTO producers (id, name) VALUES (240,'CBS');
INSERT INTO producers (id, name) VALUES (241,'CCTV Animation');
INSERT INTO producers (id, name) VALUES (242,'CD Projekt Red');
INSERT INTO producers (id, name) VALUES (243,'CEKAI');
INSERT INTO producers (id, name) VALUES (244,'Celsys');
INSERT INTO producers (id, name) VALUES (245,'CG Year');
INSERT INTO producers (id, name) VALUES (246,'CHANCE iN');
INSERT INTO producers (id, name) VALUES (247,'chara-ani.com');
INSERT INTO producers (id, name) VALUES (248,'CherryLips');
INSERT INTO producers (id, name) VALUES (249,'ChiChinoya');
INSERT INTO producers (id, name) VALUES (250,'Children''s Playground Entertainment');
INSERT INTO producers (id, name) VALUES (251,'China Animation Characters');
INSERT INTO producers (id, name) VALUES (252,'China Film Animation');
INSERT INTO producers (id, name) VALUES (253,'China Literature Limited');
INSERT INTO producers (id, name) VALUES (254,'China South Angel');
INSERT INTO producers (id, name) VALUES (255,'Chippai');
INSERT INTO producers (id, name) VALUES (256,'Chiptune');
INSERT INTO producers (id, name) VALUES (257,'CHOCOLATE');
INSERT INTO producers (id, name) VALUES (258,'Chongzhuo Animation');
INSERT INTO producers (id, name) VALUES (259,'Chosen');
INSERT INTO producers (id, name) VALUES (260,'Christmas Holly');
INSERT INTO producers (id, name) VALUES (261,'Chrono Gear Creative');
INSERT INTO producers (id, name) VALUES (262,'ChuChu');
INSERT INTO producers (id, name) VALUES (263,'Chugai Mining');
INSERT INTO producers (id, name) VALUES (264,'Chukong Technologies');
INSERT INTO producers (id, name) VALUES (265,'Chukyo TV Broadcasting');
INSERT INTO producers (id, name) VALUES (266,'Chungeorahm Film');
INSERT INTO producers (id, name) VALUES (267,'Chuubu Nihon Kyouei');
INSERT INTO producers (id, name) VALUES (268,'CIC');
INSERT INTO producers (id, name) VALUES (269,'Cinema Tohoku');
INSERT INTO producers (id, name) VALUES (270,'CinePix');
INSERT INTO producers (id, name) VALUES (271,'Cloud Art');
INSERT INTO producers (id, name) VALUES (272,'Cloud22');
INSERT INTO producers (id, name) VALUES (273,'CMC MEDIA');
INSERT INTO producers (id, name) VALUES (274,'CMI');
INSERT INTO producers (id, name) VALUES (275,'Coamix');
INSERT INTO producers (id, name) VALUES (276,'Coastline Animation Studio');
INSERT INTO producers (id, name) VALUES (277,'Cocoro Free');
INSERT INTO producers (id, name) VALUES (278,'Code');
INSERT INTO producers (id, name) VALUES (279,'COLOPL');
INSERT INTO producers (id, name) VALUES (280,'Colored Pencil Animation');
INSERT INTO producers (id, name) VALUES (281,'Colored Pencil Animation Japan');
INSERT INTO producers (id, name) VALUES (282,'Comic Animation');
INSERT INTO producers (id, name) VALUES (283,'Comic Umenohone');
INSERT INTO producers (id, name) VALUES (284,'comico');
INSERT INTO producers (id, name) VALUES (285,'COMICSMART');
INSERT INTO producers (id, name) VALUES (286,'CoMix Wave Films');
INSERT INTO producers (id, name) VALUES (287,'Comma Studio');
INSERT INTO producers (id, name) VALUES (288,'Company AZA');
INSERT INTO producers (id, name) VALUES (289,'Composition Inc.');
INSERT INTO producers (id, name) VALUES (290,'CompTown');
INSERT INTO producers (id, name) VALUES (291,'Comstock');
INSERT INTO producers (id, name) VALUES (292,'Contents Seed');
INSERT INTO producers (id, name) VALUES (293,'Cookie Jar Entertainment');
INSERT INTO producers (id, name) VALUES (294,'Coolism Productions');
INSERT INTO producers (id, name) VALUES (295,'Cosmic Ray');
INSERT INTO producers (id, name) VALUES (296,'Cosmos');
INSERT INTO producers (id, name) VALUES (297,'Cospa');
INSERT INTO producers (id, name) VALUES (298,'Cotton Doll');
INSERT INTO producers (id, name) VALUES (299,'Craftar Studios');
INSERT INTO producers (id, name) VALUES (300,'Craftsman Animation');
INSERT INTO producers (id, name) VALUES (301,'Cranberry');
INSERT INTO producers (id, name) VALUES (302,'Creative Bridge');
INSERT INTO producers (id, name) VALUES (303,'Creative Power Entertaining');
INSERT INTO producers (id, name) VALUES (304,'Creators in Pack');
INSERT INTO producers (id, name) VALUES (305,'Creatures Inc.');
INSERT INTO producers (id, name) VALUES (306,'Creek');
INSERT INTO producers (id, name) VALUES (307,'Creek & River');
INSERT INTO producers (id, name) VALUES (308,'CREi');
INSERT INTO producers (id, name) VALUES (309,'Crest');
INSERT INTO producers (id, name) VALUES (310,'Cromea');
INSERT INTO producers (id, name) VALUES (311,'Crossphere');
INSERT INTO producers (id, name) VALUES (312,'Crown Records');
INSERT INTO producers (id, name) VALUES (313,'Crunchyroll');
INSERT INTO producers (id, name) VALUES (314,'Crunchyroll SC Anime Fund');
INSERT INTO producers (id, name) VALUES (315,'CTW');
INSERT INTO producers (id, name) VALUES (316,'CUCURI');
INSERT INTO producers (id, name) VALUES (317,'Culture Entertainment');
INSERT INTO producers (id, name) VALUES (318,'Culture Publishers');
INSERT INTO producers (id, name) VALUES (319,'CyberAgent');
INSERT INTO producers (id, name) VALUES (320,'CyberConnect2');
INSERT INTO producers (id, name) VALUES (321,'CyberStep');
INSERT INTO producers (id, name) VALUES (322,'Cyclone Graphics');
INSERT INTO producers (id, name) VALUES (323,'Cygames');
INSERT INTO producers (id, name) VALUES (324,'D & D Pictures');
INSERT INTO producers (id, name) VALUES (325,'D&C WEBTOON Biz');
INSERT INTO producers (id, name) VALUES (326,'d-rights');
INSERT INTO producers (id, name) VALUES (327,'D-techno');
INSERT INTO producers (id, name) VALUES (328,'D.N. Dream Partners');
INSERT INTO producers (id, name) VALUES (329,'D.ROCK-ART');
INSERT INTO producers (id, name) VALUES (330,'D3');
INSERT INTO producers (id, name) VALUES (331,'Da Huoniao Donghua');
INSERT INTO producers (id, name) VALUES (332,'Daewon Media');
INSERT INTO producers (id, name) VALUES (333,'Dai Nippon Printing');
INSERT INTO producers (id, name) VALUES (334,'Daiei');
INSERT INTO producers (id, name) VALUES (335,'Daiichi Shokai');
INSERT INTO producers (id, name) VALUES (336,'Daiichikosho');
INSERT INTO producers (id, name) VALUES (337,'Daiko');
INSERT INTO producers (id, name) VALUES (338,'Daily Vision');
INSERT INTO producers (id, name) VALUES (339,'Daito Giken');
INSERT INTO producers (id, name) VALUES (340,'DandeLion Animation Studio');
INSERT INTO producers (id, name) VALUES (341,'Darts');
INSERT INTO producers (id, name) VALUES (342,'Datam Polystar');
INSERT INTO producers (id, name) VALUES (343,'Daume');
INSERT INTO producers (id, name) VALUES (344,'DAX Production');
INSERT INTO producers (id, name) VALUES (345,'Days');
INSERT INTO producers (id, name) VALUES (346,'Dear Stage inc.');
INSERT INTO producers (id, name) VALUES (347,'Decovocal');
INSERT INTO producers (id, name) VALUES (348,'Deho Gallery');
INSERT INTO producers (id, name) VALUES (349,'Delfi Sound');
INSERT INTO producers (id, name) VALUES (350,'Delightworks');
INSERT INTO producers (id, name) VALUES (351,'DeNA');
INSERT INTO producers (id, name) VALUES (352,'Dentsu');
INSERT INTO producers (id, name) VALUES (353,'Dentsu Eigasha Tokyo');
INSERT INTO producers (id, name) VALUES (354,'Dentsu Meitetsu Communications');
INSERT INTO producers (id, name) VALUES (355,'Dentsu Razorfish');
INSERT INTO producers (id, name) VALUES (356,'Dentsu Tec');
INSERT INTO producers (id, name) VALUES (357,'Design Factory');
INSERT INTO producers (id, name) VALUES (358,'DiC Entertainment');
INSERT INTO producers (id, name) VALUES (359,'Digital Frontier');
INSERT INTO producers (id, name) VALUES (360,'Digital Media Lab');
INSERT INTO producers (id, name) VALUES (361,'Digital Network Animation');
INSERT INTO producers (id, name) VALUES (362,'Digital Works');
INSERT INTO producers (id, name) VALUES (363,'Digiturbo');
INSERT INTO producers (id, name) VALUES (364,'Digiview Productions');
INSERT INTO producers (id, name) VALUES (365,'Diomedéa');
INSERT INTO producers (id, name) VALUES (366,'Directions');
INSERT INTO producers (id, name) VALUES (367,'Discovery');
INSERT INTO producers (id, name) VALUES (368,'Disney Animation China');
INSERT INTO producers (id, name) VALUES (369,'Disney Platform Distribution');
INSERT INTO producers (id, name) VALUES (370,'DIVE II Entertainment');
INSERT INTO producers (id, name) VALUES (371,'Diwphalanx Records');
INSERT INTO producers (id, name) VALUES (372,'DJI');
INSERT INTO producers (id, name) VALUES (373,'DLE');
INSERT INTO producers (id, name) VALUES (374,'DMM Music');
INSERT INTO producers (id, name) VALUES (375,'DMM pictures');
INSERT INTO producers (id, name) VALUES (376,'DMM.com');
INSERT INTO producers (id, name) VALUES (377,'DMM.com Labo');
INSERT INTO producers (id, name) VALUES (378,'DMM.futureworks');
INSERT INTO producers (id, name) VALUES (379,'Docomo Anime Store');
INSERT INTO producers (id, name) VALUES (380,'DOGA Productions');
INSERT INTO producers (id, name) VALUES (381,'Dokidoki Factory');
INSERT INTO producers (id, name) VALUES (382,'Dongwoo A&E');
INSERT INTO producers (id, name) VALUES (383,'Dongyang Animation');
INSERT INTO producers (id, name) VALUES (384,'Donuts');
INSERT INTO producers (id, name) VALUES (385,'DR Movie');
INSERT INTO producers (id, name) VALUES (386,'Dream Creation');
INSERT INTO producers (id, name) VALUES (387,'Dream Force');
INSERT INTO producers (id, name) VALUES (388,'Dream Shift');
INSERT INTO producers (id, name) VALUES (389,'Drecom');
INSERT INTO producers (id, name) VALUES (390,'Duckbill Entertainment');
INSERT INTO producers (id, name) VALUES (391,'dugout');
INSERT INTO producers (id, name) VALUES (392,'Dwango');
INSERT INTO producers (id, name) VALUES (393,'Dwango Music Entertainment');
INSERT INTO producers (id, name) VALUES (394,'dwarf');
INSERT INTO producers (id, name) VALUES (395,'Dynamic Media Pictures');
INSERT INTO producers (id, name) VALUES (396,'Dynamic Planning');
INSERT INTO producers (id, name) VALUES (397,'Dynamo Pictures');
INSERT INTO producers (id, name) VALUES (398,'E&G Films');
INSERT INTO producers (id, name) VALUES (399,'e-notion');
INSERT INTO producers (id, name) VALUES (400,'Earth Star Entertainment');
INSERT INTO producers (id, name) VALUES (401,'eBooK Initiative Japan');
INSERT INTO producers (id, name) VALUES (402,'EBS');
INSERT INTO producers (id, name) VALUES (403,'Echo');
INSERT INTO producers (id, name) VALUES (404,'Echoes');
INSERT INTO producers (id, name) VALUES (405,'EDGE');
INSERT INTO producers (id, name) VALUES (406,'Egg Firm');
INSERT INTO producers (id, name) VALUES (407,'eigoMANGA');
INSERT INTO producers (id, name) VALUES (408,'ElectromagneticWave');
INSERT INTO producers (id, name) VALUES (409,'ELF-IN');
INSERT INTO producers (id, name) VALUES (410,'EMI');
INSERT INTO producers (id, name) VALUES (411,'Emon');
INSERT INTO producers (id, name) VALUES (412,'Encourage Films');
INSERT INTO producers (id, name) VALUES (413,'Enoki Films');
INSERT INTO producers (id, name) VALUES (414,'ensky');
INSERT INTO producers (id, name) VALUES (415,'entama');
INSERT INTO producers (id, name) VALUES (416,'Enterbrain');
INSERT INTO producers (id, name) VALUES (417,'Epicross');
INSERT INTO producers (id, name) VALUES (418,'Epoch');
INSERT INTO producers (id, name) VALUES (419,'eStream');
INSERT INTO producers (id, name) VALUES (420,'Eswood');
INSERT INTO producers (id, name) VALUES (421,'Evil Line Records');
INSERT INTO producers (id, name) VALUES (422,'Exa International');
INSERT INTO producers (id, name) VALUES (423,'Exit Tunes');
INSERT INTO producers (id, name) VALUES (424,'EXNOA');
INSERT INTO producers (id, name) VALUES (425,'Eye Move');
INSERT INTO producers (id, name) VALUES (426,'F.M.F');
INSERT INTO producers (id, name) VALUES (427,'f4samurai');
INSERT INTO producers (id, name) VALUES (428,'FABTONE');
INSERT INTO producers (id, name) VALUES (429,'Fairy Dust');
INSERT INTO producers (id, name) VALUES (430,'famima.com');
INSERT INTO producers (id, name) VALUES (431,'Fan Company');
INSERT INTO producers (id, name) VALUES (432,'FanFan Inc.');
INSERT INTO producers (id, name) VALUES (433,'Fantawild Animation');
INSERT INTO producers (id, name) VALUES (434,'Fanworks');
INSERT INTO producers (id, name) VALUES (435,'FBC');
INSERT INTO producers (id, name) VALUES (436,'feel.');
INSERT INTO producers (id, name) VALUES (437,'Felicity');
INSERT INTO producers (id, name) VALUES (438,'Felix Film');
INSERT INTO producers (id, name) VALUES (439,'feng');
INSERT INTO producers (id, name) VALUES (440,'Fengyun Animation');
INSERT INTO producers (id, name) VALUES (441,'Fenz');
INSERT INTO producers (id, name) VALUES (442,'Fever Dreams');
INSERT INTO producers (id, name) VALUES (443,'Fields');
INSERT INTO producers (id, name) VALUES (444,'Film Workshop');
INSERT INTO producers (id, name) VALUES (445,'Filmlink International');
INSERT INTO producers (id, name) VALUES (446,'FILMONY');
INSERT INTO producers (id, name) VALUES (447,'FIREBUG');
INSERT INTO producers (id, name) VALUES (448,'Five Ways');
INSERT INTO producers (id, name) VALUES (449,'flaggs');
INSERT INTO producers (id, name) VALUES (450,'FLAGSHIP LINE');
INSERT INTO producers (id, name) VALUES (451,'Flat Studio');
INSERT INTO producers (id, name) VALUES (452,'Flex Comix');
INSERT INTO producers (id, name) VALUES (453,'flying DOG');
INSERT INTO producers (id, name) VALUES (454,'Foch Films');
INSERT INTO producers (id, name) VALUES (455,'Forces11');
INSERT INTO producers (id, name) VALUES (456,'Forecast Communications');
INSERT INTO producers (id, name) VALUES (457,'FOREST Hunting One');
INSERT INTO producers (id, name) VALUES (458,'Fosun Entertainment Japan');
INSERT INTO producers (id, name) VALUES (459,'Four Some');
INSERT INTO producers (id, name) VALUES (460,'Free-Will');
INSERT INTO producers (id, name) VALUES (461,'Frencel');
INSERT INTO producers (id, name) VALUES (462,'Friendly Land');
INSERT INTO producers (id, name) VALUES (463,'Front Line');
INSERT INTO producers (id, name) VALUES (464,'Front Wing');
INSERT INTO producers (id, name) VALUES (465,'Frontier Works');
INSERT INTO producers (id, name) VALUES (466,'Fuji Creative');
INSERT INTO producers (id, name) VALUES (467,'Fuji TV');
INSERT INTO producers (id, name) VALUES (468,'Fuji Video');
INSERT INTO producers (id, name) VALUES (469,'Fuji&gumi Games');
INSERT INTO producers (id, name) VALUES (470,'Fujian Ziyan Animation Technology');
INSERT INTO producers (id, name) VALUES (471,'Fujiko F. Fujio Pro');
INSERT INTO producers (id, name) VALUES (472,'Fujimi Shobo');
INSERT INTO producers (id, name) VALUES (473,'Fujio Production');
INSERT INTO producers (id, name) VALUES (474,'Fujipacific Music');
INSERT INTO producers (id, name) VALUES (475,'Fujishouji');
INSERT INTO producers (id, name) VALUES (476,'FUJIYAMA PROJECT JAPAN');
INSERT INTO producers (id, name) VALUES (477,'Fukuoka Broadcasting System');
INSERT INTO producers (id, name) VALUES (478,'Funimation');
INSERT INTO producers (id, name) VALUES (479,'FuRyu');
INSERT INTO producers (id, name) VALUES (480,'Futabasha');
INSERT INTO producers (id, name) VALUES (481,'Future Animation Factory');
INSERT INTO producers (id, name) VALUES (482,'FUTURE LEAP');
INSERT INTO producers (id, name) VALUES (483,'Future Planet');
INSERT INTO producers (id, name) VALUES (484,'G holdings');
INSERT INTO producers (id, name) VALUES (485,'G&G Entertainment');
INSERT INTO producers (id, name) VALUES (486,'G-mode');
INSERT INTO producers (id, name) VALUES (487,'GAGA');
INSERT INTO producers (id, name) VALUES (488,'Gainax');
INSERT INTO producers (id, name) VALUES (489,'Gakken');
INSERT INTO producers (id, name) VALUES (490,'Gakken Eigakyoku');
INSERT INTO producers (id, name) VALUES (491,'Gallop');
INSERT INTO producers (id, name) VALUES (492,'Gamegate');
INSERT INTO producers (id, name) VALUES (493,'GANSIS');
INSERT INTO producers (id, name) VALUES (494,'GARNET');
INSERT INTO producers (id, name) VALUES (495,'GDH');
INSERT INTO producers (id, name) VALUES (496,'Geek Pictures');
INSERT INTO producers (id, name) VALUES (497,'Geidai Animation');
INSERT INTO producers (id, name) VALUES (498,'Geijutsu Eigasha');
INSERT INTO producers (id, name) VALUES (499,'GEN Productions');
INSERT INTO producers (id, name) VALUES (500,'Gen''ei');
INSERT INTO producers (id, name) VALUES (501,'Genco');
INSERT INTO producers (id, name) VALUES (502,'Gendai Production');
INSERT INTO producers (id, name) VALUES (503,'Geneon Universal Entertainment');
INSERT INTO producers (id, name) VALUES (504,'Genie Music');
INSERT INTO producers (id, name) VALUES (505,'Gentosha Comics');
INSERT INTO producers (id, name) VALUES (506,'Gigno Systems');
INSERT INTO producers (id, name) VALUES (507,'gimik');
INSERT INTO producers (id, name) VALUES (508,'Ginga Ya');
INSERT INTO producers (id, name) VALUES (509,'GKIDS');
INSERT INTO producers (id, name) VALUES (510,'Glams');
INSERT INTO producers (id, name) VALUES (511,'Global Digital Creations');
INSERT INTO producers (id, name) VALUES (512,'Global Solutions');
INSERT INTO producers (id, name) VALUES (513,'Glovision');
INSERT INTO producers (id, name) VALUES (514,'GODxDOG Production');
INSERT INTO producers (id, name) VALUES (515,'GoGo Visual Planning');
INSERT INTO producers (id, name) VALUES (516,'Gold Bear');
INSERT INTO producers (id, name) VALUES (517,'Gonzo');
INSERT INTO producers (id, name) VALUES (518,'Good Smile Company');
INSERT INTO producers (id, name) VALUES (519,'Good Smile Film');
INSERT INTO producers (id, name) VALUES (520,'GOON TRAX');
INSERT INTO producers (id, name) VALUES (521,'Gorilla Pictures');
INSERT INTO producers (id, name) VALUES (522,'Goto Inc.');
INSERT INTO producers (id, name) VALUES (523,'Graduate School of Film Producing');
INSERT INTO producers (id, name) VALUES (524,'GRANTdesign');
INSERT INTO producers (id, name) VALUES (525,'Graphinica');
INSERT INTO producers (id, name) VALUES (526,'Grasshoppa!');
INSERT INTO producers (id, name) VALUES (527,'GREE');
INSERT INTO producers (id, name) VALUES (528,'GREE Entertainment');
INSERT INTO producers (id, name) VALUES (529,'Green Bunny');
INSERT INTO producers (id, name) VALUES (530,'Greenwood');
INSERT INTO producers (id, name) VALUES (531,'Grooove');
INSERT INTO producers (id, name) VALUES (532,'Group TAC');
INSERT INTO producers (id, name) VALUES (533,'Grouper Productions');
INSERT INTO producers (id, name) VALUES (534,'GungHo Online Entertainment');
INSERT INTO producers (id, name) VALUES (535,'GYAO!');
INSERT INTO producers (id, name) VALUES (536,'Gzbrain');
INSERT INTO producers (id, name) VALUES (537,'Hakoniwa Academy Student Council');
INSERT INTO producers (id, name) VALUES (538,'Hakuhodo');
INSERT INTO producers (id, name) VALUES (539,'Hakuhodo DY Media Partners');
INSERT INTO producers (id, name) VALUES (540,'Hakuhodo DY Music & Pictures');
INSERT INTO producers (id, name) VALUES (541,'Hakusensha');
INSERT INTO producers (id, name) VALUES (542,'Hal Film Maker');
INSERT INTO producers (id, name) VALUES (543,'Half H.P Studio');
INSERT INTO producers (id, name) VALUES (544,'Half HP Studio');
INSERT INTO producers (id, name) VALUES (545,'Haneda xR Studio');
INSERT INTO producers (id, name) VALUES (546,'Hanho Heung-Up');
INSERT INTO producers (id, name) VALUES (547,'Haoliners Animation League');
INSERT INTO producers (id, name) VALUES (548,'Haowan Dongman');
INSERT INTO producers (id, name) VALUES (549,'Happinet');
INSERT INTO producers (id, name) VALUES (550,'Happinet Media Marketing');
INSERT INTO producers (id, name) VALUES (551,'Happinet Phantom Studios');
INSERT INTO producers (id, name) VALUES (552,'Happinet Pictures');
INSERT INTO producers (id, name) VALUES (553,'Happy Elements');
INSERT INTO producers (id, name) VALUES (554,'Harappa');
INSERT INTO producers (id, name) VALUES (555,'Harmony Gold');
INSERT INTO producers (id, name) VALUES (556,'Hasbro');
INSERT INTO producers (id, name) VALUES (557,'Hawkeye');
INSERT INTO producers (id, name) VALUES (558,'Hayakawa Shobou');
INSERT INTO producers (id, name) VALUES (559,'Heart Company');
INSERT INTO producers (id, name) VALUES (560,'HeART-BIT');
INSERT INTO producers (id, name) VALUES (561,'Heewon Entertainment');
INSERT INTO producers (id, name) VALUES (562,'Heiwa');
INSERT INTO producers (id, name) VALUES (563,'Hero Communication');
INSERT INTO producers (id, name) VALUES (564,'Heroz');
INSERT INTO producers (id, name) VALUES (565,'Hexagon Pictures');
INSERT INTO producers (id, name) VALUES (566,'HIAN');
INSERT INTO producers (id, name) VALUES (567,'Hifumi Shobo');
INSERT INTO producers (id, name) VALUES (568,'Higa Brothers Production');
INSERT INTO producers (id, name) VALUES (569,'High Energy Studio');
INSERT INTO producers (id, name) VALUES (570,'High Kick Entertainment');
INSERT INTO producers (id, name) VALUES (571,'Highlights Entertainment');
INSERT INTO producers (id, name) VALUES (572,'Hikari TV');
INSERT INTO producers (id, name) VALUES (573,'Himajin Planning');
INSERT INTO producers (id, name) VALUES (574,'Himeyuri Alumnae Incorporated Foundation');
INSERT INTO producers (id, name) VALUES (575,'Hipland Music Corporation');
INSERT INTO producers (id, name) VALUES (576,'Hiro Media');
INSERT INTO producers (id, name) VALUES (577,'Hiroshi Planning');
INSERT INTO producers (id, name) VALUES (578,'Hiroshima City University');
INSERT INTO producers (id, name) VALUES (579,'Hiroshima Television');
INSERT INTO producers (id, name) VALUES (580,'Hisashishi Videos');
INSERT INTO producers (id, name) VALUES (581,'HJ Holdings');
INSERT INTO producers (id, name) VALUES (582,'HM Heros');
INSERT INTO producers (id, name) VALUES (583,'HOBBY BASE Yellow Submarine');
INSERT INTO producers (id, name) VALUES (584,'Hobby Japan');
INSERT INTO producers (id, name) VALUES (585,'Hobi Animation');
INSERT INTO producers (id, name) VALUES (586,'Hobibox');
INSERT INTO producers (id, name) VALUES (587,'Hochi Shimbun');
INSERT INTO producers (id, name) VALUES (588,'Hokkaido Azmacy');
INSERT INTO producers (id, name) VALUES (589,'Hokkaido Cultural Broadcasting');
INSERT INTO producers (id, name) VALUES (590,'Hololive Production');
INSERT INTO producers (id, name) VALUES (591,'Hoods Entertainment');
INSERT INTO producers (id, name) VALUES (592,'Horgos Coloroom Pictures Co.');
INSERT INTO producers (id, name) VALUES (593,'Horgos Huotian Dayou');
INSERT INTO producers (id, name) VALUES (594,'HoriPro');
INSERT INTO producers (id, name) VALUES (595,'HoriPro International');
INSERT INTO producers (id, name) VALUES (596,'Hoso Seisaku Doga');
INSERT INTO producers (id, name) VALUES (597,'Hot Bear');
INSERT INTO producers (id, name) VALUES (598,'HOTZIPANG');
INSERT INTO producers (id, name) VALUES (599,'Houbunsha');
INSERT INTO producers (id, name) VALUES (600,'Huaxia Film Distribution');
INSERT INTO producers (id, name) VALUES (601,'Huayi Brothers Animation');
INSERT INTO producers (id, name) VALUES (602,'Hulu');
INSERT INTO producers (id, name) VALUES (603,'Hypergryph');
INSERT INTO producers (id, name) VALUES (604,'I Will');
INSERT INTO producers (id, name) VALUES (605,'I''m Enterprise');
INSERT INTO producers (id, name) VALUES (606,'I.Toon');
INSERT INTO producers (id, name) VALUES (607,'i0+');
INSERT INTO producers (id, name) VALUES (608,'ibis Capital Partners');
INSERT INTO producers (id, name) VALUES (609,'Ichigo Animation');
INSERT INTO producers (id, name) VALUES (610,'Ichijinsha');
INSERT INTO producers (id, name) VALUES (611,'Ichikara Inc.');
INSERT INTO producers (id, name) VALUES (612,'Idea Factory');
INSERT INTO producers (id, name) VALUES (613,'Idol');
INSERT INTO producers (id, name) VALUES (614,'iDRAGONS Creative Studio');
INSERT INTO producers (id, name) VALUES (615,'iDreamSky');
INSERT INTO producers (id, name) VALUES (616,'ILCA');
INSERT INTO producers (id, name) VALUES (617,'Illumitoon Entertainment');
INSERT INTO producers (id, name) VALUES (618,'Ima Group');
INSERT INTO producers (id, name) VALUES (619,'Image House');
INSERT INTO producers (id, name) VALUES (620,'Image Kei');
INSERT INTO producers (id, name) VALUES (621,'Imagi');
INSERT INTO producers (id, name) VALUES (622,'Imagica');
INSERT INTO producers (id, name) VALUES (623,'IMAGICA Lab.');
INSERT INTO producers (id, name) VALUES (624,'Imagica West');
INSERT INTO producers (id, name) VALUES (625,'Imagin');
INSERT INTO producers (id, name) VALUES (626,'ImaginAsian Entertainment');
INSERT INTO producers (id, name) VALUES (627,'Imagine');
INSERT INTO producers (id, name) VALUES (628,'Imagineer');
INSERT INTO producers (id, name) VALUES (629,'Inc.');
INSERT INTO producers (id, name) VALUES (630,'Include P.D.');
INSERT INTO producers (id, name) VALUES (631,'INCS toenter');
INSERT INTO producers (id, name) VALUES (632,'Indeprox');
INSERT INTO producers (id, name) VALUES (633,'Index');
INSERT INTO producers (id, name) VALUES (634,'indigo line');
INSERT INTO producers (id, name) VALUES (635,'Infinite');
INSERT INTO producers (id, name) VALUES (636,'Infinity Animations');
INSERT INTO producers (id, name) VALUES (637,'Information-technology Promotion Agency');
INSERT INTO producers (id, name) VALUES (638,'ING');
INSERT INTO producers (id, name) VALUES (639,'Innocent Grey');
INSERT INTO producers (id, name) VALUES (640,'INoNaKa Music');
INSERT INTO producers (id, name) VALUES (641,'INSPION Edge');
INSERT INTO producers (id, name) VALUES (642,'International Digital Artist');
INSERT INTO producers (id, name) VALUES (643,'iQIYI');
INSERT INTO producers (id, name) VALUES (644,'Irem Software Engineering');
INSERT INTO producers (id, name) VALUES (645,'IRMA LA DOUCE');
INSERT INTO producers (id, name) VALUES (646,'Ishimori Pro');
INSERT INTO producers (id, name) VALUES (647,'it''s');
INSERT INTO producers (id, name) VALUES (648,'Iwatobi High School Swimming Club');
INSERT INTO producers (id, name) VALUES (649,'Iyasakadou Film');
INSERT INTO producers (id, name) VALUES (650,'J.C.Staff');
INSERT INTO producers (id, name) VALUES (651,'J.T.P.P.');
INSERT INTO producers (id, name) VALUES (652,'Jade Animation');
INSERT INTO producers (id, name) VALUES (653,'Jam');
INSERT INTO producers (id, name) VALUES (654,'Japan Home Video');
INSERT INTO producers (id, name) VALUES (655,'Japan Sleeve');
INSERT INTO producers (id, name) VALUES (656,'Japan Volleyball Association');
INSERT INTO producers (id, name) VALUES (657,'Jay Zone Comic');
INSERT INTO producers (id, name) VALUES (658,'jeux d''eau');
INSERT INTO producers (id, name) VALUES (659,'Jidaigeki Channel');
INSERT INTO producers (id, name) VALUES (660,'Jilin Yushuo Entertainment');
INSERT INTO producers (id, name) VALUES (661,'Jinnan Studio');
INSERT INTO producers (id, name) VALUES (662,'Jinnis Animation Studios');
INSERT INTO producers (id, name) VALUES (663,'JM Animation');
INSERT INTO producers (id, name) VALUES (664,'JP Room');
INSERT INTO producers (id, name) VALUES (665,'JR East Marketing & Communications');
INSERT INTO producers (id, name) VALUES (666,'JTB Entertainment');
INSERT INTO producers (id, name) VALUES (667,'JTB Next Creation');
INSERT INTO producers (id, name) VALUES (668,'Jumondo');
INSERT INTO producers (id, name) VALUES (669,'Just Production');
INSERT INTO producers (id, name) VALUES (670,'JY Animation');
INSERT INTO producers (id, name) VALUES (671,'K contents');
INSERT INTO producers (id, name) VALUES (672,'K-Factory');
INSERT INTO producers (id, name) VALUES (673,'Kadokawa');
INSERT INTO producers (id, name) VALUES (674,'Kadokawa Animation');
INSERT INTO producers (id, name) VALUES (675,'Kadokawa Contents Gate');
INSERT INTO producers (id, name) VALUES (676,'Kadokawa Haruki Corporation');
INSERT INTO producers (id, name) VALUES (677,'Kadokawa Media (Taiwan)');
INSERT INTO producers (id, name) VALUES (678,'Kadokawa Media House');
INSERT INTO producers (id, name) VALUES (679,'Kadokawa Pictures Japan');
INSERT INTO producers (id, name) VALUES (680,'Kadokawa Shoten');
INSERT INTO producers (id, name) VALUES (681,'Kaeruotoko Shokai');
INSERT INTO producers (id, name) VALUES (682,'KAGAYA Studio');
INSERT INTO producers (id, name) VALUES (683,'Kaibutsu');
INSERT INTO producers (id, name) VALUES (684,'Kakao Japan');
INSERT INTO producers (id, name) VALUES (685,'Kamikaze Douga');
INSERT INTO producers (id, name) VALUES (686,'Kamimine-chou');
INSERT INTO producers (id, name) VALUES (687,'Kamio Japan');
INSERT INTO producers (id, name) VALUES (688,'Kamitsubaki Studio');
INSERT INTO producers (id, name) VALUES (689,'Kanade Creative');
INSERT INTO producers (id, name) VALUES (690,'Kanetsu Investment');
INSERT INTO producers (id, name) VALUES (691,'Kanon Sound');
INSERT INTO producers (id, name) VALUES (692,'Kansai Telecasting');
INSERT INTO producers (id, name) VALUES (693,'Kate Arrow');
INSERT INTO producers (id, name) VALUES (694,'Katsudou-manga-kan');
INSERT INTO producers (id, name) VALUES (695,'Kawade Shobo Shinsha');
INSERT INTO producers (id, name) VALUES (696,'Kawamoto Productions');
INSERT INTO producers (id, name) VALUES (697,'KBS');
INSERT INTO producers (id, name) VALUES (698,'KBS Kyoto');
INSERT INTO producers (id, name) VALUES (699,'KDDI');
INSERT INTO producers (id, name) VALUES (700,'Keisei Electric Railway');
INSERT INTO producers (id, name) VALUES (701,'KEN ON');
INSERT INTO producers (id, name) VALUES (702,'Kenji Studio');
INSERT INTO producers (id, name) VALUES (703,'KENMedia');
INSERT INTO producers (id, name) VALUES (704,'Khara');
INSERT INTO producers (id, name) VALUES (705,'Ki/oon Music');
INSERT INTO producers (id, name) VALUES (706,'Kids Station');
INSERT INTO producers (id, name) VALUES (707,'Kill Time Communication');
INSERT INTO producers (id, name) VALUES (708,'King Bee');
INSERT INTO producers (id, name) VALUES (709,'King Records');
INSERT INTO producers (id, name) VALUES (710,'Kino Production');
INSERT INTO producers (id, name) VALUES (711,'Kinoshita Group Holdings');
INSERT INTO producers (id, name) VALUES (712,'Kinoshita Koumuten');
INSERT INTO producers (id, name) VALUES (713,'Kinoshita Management');
INSERT INTO producers (id, name) VALUES (714,'Kinyosha');
INSERT INTO producers (id, name) VALUES (715,'Kitty Film Mitaka Studio');
INSERT INTO producers (id, name) VALUES (716,'Kitty Films');
INSERT INTO producers (id, name) VALUES (717,'Kiyosumi High School Mahjong Club');
INSERT INTO producers (id, name) VALUES (718,'Kizuna AI');
INSERT INTO producers (id, name) VALUES (719,'KJJ Animation');
INSERT INTO producers (id, name) VALUES (720,'KLab');
INSERT INTO producers (id, name) VALUES (721,'KlockWorx');
INSERT INTO producers (id, name) VALUES (722,'KMMJ Studios');
INSERT INTO producers (id, name) VALUES (723,'Knack Animation');
INSERT INTO producers (id, name) VALUES (724,'Knack Productions');
INSERT INTO producers (id, name) VALUES (725,'Kobe Design University');
INSERT INTO producers (id, name) VALUES (726,'Kobunsha');
INSERT INTO producers (id, name) VALUES (727,'KOCCA Animation Studio');
INSERT INTO producers (id, name) VALUES (728,'Kodansha');
INSERT INTO producers (id, name) VALUES (729,'Koei');
INSERT INTO producers (id, name) VALUES (730,'Koei Tecmo Games');
INSERT INTO producers (id, name) VALUES (731,'Kojiro Shishido Animation Works');
INSERT INTO producers (id, name) VALUES (732,'Kokusai Eigasha');
INSERT INTO producers (id, name) VALUES (733,'Konami');
INSERT INTO producers (id, name) VALUES (734,'Konami Cross Media NY');
INSERT INTO producers (id, name) VALUES (735,'Konami Digital Entertainment');
INSERT INTO producers (id, name) VALUES (736,'KOO-KI');
INSERT INTO producers (id, name) VALUES (737,'Korean Academy of Film Arts');
INSERT INTO producers (id, name) VALUES (738,'Kotobukiya');
INSERT INTO producers (id, name) VALUES (739,'KSS');
INSERT INTO producers (id, name) VALUES (740,'Kuaikan Manhua');
INSERT INTO producers (id, name) VALUES (741,'Kujou-kun no Bonnou wo Mimamoru-kai');
INSERT INTO producers (id, name) VALUES (742,'Kuri Jikken Manga Kobo');
INSERT INTO producers (id, name) VALUES (743,'Kyodo Eiga');
INSERT INTO producers (id, name) VALUES (744,'Kyoraku Industrial Holdings');
INSERT INTO producers (id, name) VALUES (745,'Kyoto Animation');
INSERT INTO producers (id, name) VALUES (746,'Kyotoma');
INSERT INTO producers (id, name) VALUES (747,'Kyowa Film');
INSERT INTO producers (id, name) VALUES (748,'L.');
INSERT INTO producers (id, name) VALUES (749,'Laftel');
INSERT INTO producers (id, name) VALUES (750,'Lambert');
INSERT INTO producers (id, name) VALUES (751,'LAN Studio');
INSERT INTO producers (id, name) VALUES (752,'LandQ studios');
INSERT INTO producers (id, name) VALUES (753,'Langmaor');
INSERT INTO producers (id, name) VALUES (754,'Lantis');
INSERT INTO producers (id, name) VALUES (755,'Lapis');
INSERT INTO producers (id, name) VALUES (756,'Lastrum Music');
INSERT INTO producers (id, name) VALUES (757,'Laulea Works');
INSERT INTO producers (id, name) VALUES (758,'Lawson');
INSERT INTO producers (id, name) VALUES (759,'Lawson Entertainment');
INSERT INTO producers (id, name) VALUES (760,'Lawson HMV Entertainment');
INSERT INTO producers (id, name) VALUES (761,'Legs');
INSERT INTO producers (id, name) VALUES (762,'Lemon Heart');
INSERT INTO producers (id, name) VALUES (763,'Level-5');
INSERT INTO producers (id, name) VALUES (764,'Liber Entertainment');
INSERT INTO producers (id, name) VALUES (765,'Liberty Animation Studio');
INSERT INTO producers (id, name) VALUES (766,'Libre');
INSERT INTO producers (id, name) VALUES (767,'LIDENFILMS');
INSERT INTO producers (id, name) VALUES (768,'Life Work');
INSERT INTO producers (id, name) VALUES (769,'LINE Corporation');
INSERT INTO producers (id, name) VALUES (770,'LinkedBrain');
INSERT INTO producers (id, name) VALUES (771,'Links');
INSERT INTO producers (id, name) VALUES (772,'Liu Cong Animation');
INSERT INTO producers (id, name) VALUES (773,'Live Viewing Japan');
INSERT INTO producers (id, name) VALUES (774,'Liverpool');
INSERT INTO producers (id, name) VALUES (775,'Liyu Culture');
INSERT INTO producers (id, name) VALUES (776,'Locus Corporation');
INSERT INTO producers (id, name) VALUES (777,'LOGIC&MAGIC');
INSERT INTO producers (id, name) VALUES (778,'Ltd.');
INSERT INTO producers (id, name) VALUES (779,'Lucent Pictures Entertainment');
INSERT INTO producers (id, name) VALUES (780,'Lucky Paradise');
INSERT INTO producers (id, name) VALUES (781,'Lune Pictures');
INSERT INTO producers (id, name) VALUES (782,'Lute');
INSERT INTO producers (id, name) VALUES (783,'L²Studio');
INSERT INTO producers (id, name) VALUES (784,'m.o.e.');
INSERT INTO producers (id, name) VALUES (785,'M.S.C');
INSERT INTO producers (id, name) VALUES (786,'Mad Box');
INSERT INTO producers (id, name) VALUES (787,'Madhouse');
INSERT INTO producers (id, name) VALUES (788,'Mag Garden');
INSERT INTO producers (id, name) VALUES (789,'MAGES.');
INSERT INTO producers (id, name) VALUES (790,'Magic Bus');
INSERT INTO producers (id, name) VALUES (791,'Magic Capsule');
INSERT INTO producers (id, name) VALUES (792,'Magic Lantern Film');
INSERT INTO producers (id, name) VALUES (793,'Magilm Pictures');
INSERT INTO producers (id, name) VALUES (794,'MAGNET');
INSERT INTO producers (id, name) VALUES (795,'Maho Film');
INSERT INTO producers (id, name) VALUES (796,'Maikaze');
INSERT INTO producers (id, name) VALUES (797,'Mainichi Broadcasting System');
INSERT INTO producers (id, name) VALUES (798,'Mainichi Shimbun');
INSERT INTO producers (id, name) VALUES (799,'Majime Inc.');
INSERT INTO producers (id, name) VALUES (800,'Manga Productions');
INSERT INTO producers (id, name) VALUES (801,'Manhoo Culture');
INSERT INTO producers (id, name) VALUES (802,'MAPPA');
INSERT INTO producers (id, name) VALUES (803,'Marine Entertainment');
INSERT INTO producers (id, name) VALUES (804,'Maru Production');
INSERT INTO producers (id, name) VALUES (805,'Marubeni');
INSERT INTO producers (id, name) VALUES (806,'Marui Group');
INSERT INTO producers (id, name) VALUES (807,'Marvelous');
INSERT INTO producers (id, name) VALUES (808,'Marvelous AQL');
INSERT INTO producers (id, name) VALUES (809,'Mary Jane');
INSERT INTO producers (id, name) VALUES (810,'Marza Animation Planet');
INSERT INTO producers (id, name) VALUES (811,'Mattel Creations');
INSERT INTO producers (id, name) VALUES (812,'Maxell E-Cube');
INSERT INTO producers (id, name) VALUES (813,'Maxilla');
INSERT INTO producers (id, name) VALUES (814,'MAZRI');
INSERT INTO producers (id, name) VALUES (815,'Media Castle');
INSERT INTO producers (id, name) VALUES (816,'Media Do');
INSERT INTO producers (id, name) VALUES (817,'Media Factory');
INSERT INTO producers (id, name) VALUES (818,'Media Rings');
INSERT INTO producers (id, name) VALUES (819,'Media Station');
INSERT INTO producers (id, name) VALUES (820,'Mediabank');
INSERT INTO producers (id, name) VALUES (821,'MediaLink Entertainment Limited');
INSERT INTO producers (id, name) VALUES (822,'MediaNet');
INSERT INTO producers (id, name) VALUES (823,'MediaNet Pictures');
INSERT INTO producers (id, name) VALUES (824,'MediBang');
INSERT INTO producers (id, name) VALUES (825,'Medicos Entertainment');
INSERT INTO producers (id, name) VALUES (826,'Medicrie');
INSERT INTO producers (id, name) VALUES (827,'Meiji Seika');
INSERT INTO producers (id, name) VALUES (828,'Mellow Head');
INSERT INTO producers (id, name) VALUES (829,'Melonbooks');
INSERT INTO producers (id, name) VALUES (830,'Memory-Tech');
INSERT INTO producers (id, name) VALUES (831,'Meruhensha');
INSERT INTO producers (id, name) VALUES (832,'Micro House');
INSERT INTO producers (id, name) VALUES (833,'Micro Magazine Publishing');
INSERT INTO producers (id, name) VALUES (834,'Midorimatsu');
INSERT INTO producers (id, name) VALUES (835,'miHoYoAnime');
INSERT INTO producers (id, name) VALUES (836,'Miki Production');
INSERT INTO producers (id, name) VALUES (837,'Milestone Music Publishing');
INSERT INTO producers (id, name) VALUES (838,'Milkshake');
INSERT INTO producers (id, name) VALUES (839,'Milky Animation Label');
INSERT INTO producers (id, name) VALUES (840,'Milky Cartoon');
INSERT INTO producers (id, name) VALUES (841,'Mill Creek Entertainment');
INSERT INTO producers (id, name) VALUES (842,'Mime Corporation');
INSERT INTO producers (id, name) VALUES (843,'Minami Machi Bugyousho');
INSERT INTO producers (id, name) VALUES (844,'Ministry of the Navy');
INSERT INTO producers (id, name) VALUES (845,'Miracle Bus');
INSERT INTO producers (id, name) VALUES (846,'Miracle Robo');
INSERT INTO producers (id, name) VALUES (847,'Mirai Film');
INSERT INTO producers (id, name) VALUES (848,'Mirai Records');
INSERT INTO producers (id, name) VALUES (849,'Mirai-Kojo');
INSERT INTO producers (id, name) VALUES (850,'Miraicha Records');
INSERT INTO producers (id, name) VALUES (851,'Misseri Studio');
INSERT INTO producers (id, name) VALUES (852,'Mistral Japan');
INSERT INTO producers (id, name) VALUES (853,'Mitsubishi');
INSERT INTO producers (id, name) VALUES (854,'Mixer');
INSERT INTO producers (id, name) VALUES (855,'Mixi');
INSERT INTO producers (id, name) VALUES (856,'Miyagi Television Broadcasting');
INSERT INTO producers (id, name) VALUES (857,'Miyazaki Broadcasting');
INSERT INTO producers (id, name) VALUES (858,'Miyu Productions');
INSERT INTO producers (id, name) VALUES (859,'Miyuki Production');
INSERT INTO producers (id, name) VALUES (860,'MK Pictures');
INSERT INTO producers (id, name) VALUES (861,'MMDGP');
INSERT INTO producers (id, name) VALUES (862,'Mobcast');
INSERT INTO producers (id, name) VALUES (863,'monofilmo');
INSERT INTO producers (id, name) VALUES (864,'Monomusik');
INSERT INTO producers (id, name) VALUES (865,'MooGoo');
INSERT INTO producers (id, name) VALUES (866,'Mook Animation');
INSERT INTO producers (id, name) VALUES (867,'Moonbell');
INSERT INTO producers (id, name) VALUES (868,'Moonstone Cherry');
INSERT INTO producers (id, name) VALUES (869,'Mousou Jitsugen Media');
INSERT INTO producers (id, name) VALUES (870,'Movic');
INSERT INTO producers (id, name) VALUES (871,'Movie Walker');
INSERT INTO producers (id, name) VALUES (872,'MS Pictures');
INSERT INTO producers (id, name) VALUES (873,'MTV Japan');
INSERT INTO producers (id, name) VALUES (874,'Musashino Art University');
INSERT INTO producers (id, name) VALUES (875,'Muse Communication');
INSERT INTO producers (id, name) VALUES (876,'Muse International');
INSERT INTO producers (id, name) VALUES (877,'Mushi Production');
INSERT INTO producers (id, name) VALUES (878,'Music Brains');
INSERT INTO producers (id, name) VALUES (879,'MusicRay’n');
INSERT INTO producers (id, name) VALUES (880,'My Theater D.D.');
INSERT INTO producers (id, name) VALUES (881,'Myrica Music');
INSERT INTO producers (id, name) VALUES (882,'Myung Films');
INSERT INTO producers (id, name) VALUES (883,'Möbius Tone');
INSERT INTO producers (id, name) VALUES (884,'N&G Production');
INSERT INTO producers (id, name) VALUES (885,'NADA Holdings');
INSERT INTO producers (id, name) VALUES (886,'Nagoya Broadcasting Network');
INSERT INTO producers (id, name) VALUES (887,'Nagoya University of Arts and Sciences');
INSERT INTO producers (id, name) VALUES (888,'Nakamura Production');
INSERT INTO producers (id, name) VALUES (889,'Namisokan');
INSERT INTO producers (id, name) VALUES (890,'NANON CREATIVE');
INSERT INTO producers (id, name) VALUES (891,'Natural High');
INSERT INTO producers (id, name) VALUES (892,'Naver Webtoons');
INSERT INTO producers (id, name) VALUES (893,'NAZ');
INSERT INTO producers (id, name) VALUES (894,'NBCUniversal Entertainment Japan');
INSERT INTO producers (id, name) VALUES (895,'NEC Avenue');
INSERT INTO producers (id, name) VALUES (896,'Neft Film');
INSERT INTO producers (id, name) VALUES (897,'Nelke Planning');
INSERT INTO producers (id, name) VALUES (898,'Nelvana');
INSERT INTO producers (id, name) VALUES (899,'NetEase');
INSERT INTO producers (id, name) VALUES (900,'Netflix');
INSERT INTO producers (id, name) VALUES (901,'Network');
INSERT INTO producers (id, name) VALUES (902,'NewGin');
INSERT INTO producers (id, name) VALUES (903,'Nexon');
INSERT INTO producers (id, name) VALUES (904,'Next');
INSERT INTO producers (id, name) VALUES (905,'NEXTORY');
INSERT INTO producers (id, name) VALUES (906,'NHK');
INSERT INTO producers (id, name) VALUES (907,'NHK Enterprises');
INSERT INTO producers (id, name) VALUES (908,'NHK-BS2');
INSERT INTO producers (id, name) VALUES (909,'NHN PlayArt');
INSERT INTO producers (id, name) VALUES (910,'NIANTIC');
INSERT INTO producers (id, name) VALUES (911,'Nice Boat Animation');
INSERT INTO producers (id, name) VALUES (912,'Nichiei Agency');
INSERT INTO producers (id, name) VALUES (913,'NichiNare');
INSERT INTO producers (id, name) VALUES (914,'Nichion');
INSERT INTO producers (id, name) VALUES (915,'Nihikime no Dozeu');
INSERT INTO producers (id, name) VALUES (916,'Nihon Ad Systems');
INSERT INTO producers (id, name) VALUES (917,'Nihon Eizo');
INSERT INTO producers (id, name) VALUES (918,'Nihon Falcom');
INSERT INTO producers (id, name) VALUES (919,'Nihon Hoso Eigasha');
INSERT INTO producers (id, name) VALUES (920,'Nihon Keizai Koukokusha');
INSERT INTO producers (id, name) VALUES (921,'Nihon University College of Art');
INSERT INTO producers (id, name) VALUES (922,'Nikkatsu');
INSERT INTO producers (id, name) VALUES (923,'Nikkatsu Mukojima');
INSERT INTO producers (id, name) VALUES (924,'Nintendo');
INSERT INTO producers (id, name) VALUES (925,'Nintendo of America');
INSERT INTO producers (id, name) VALUES (926,'Nippon Animation');
INSERT INTO producers (id, name) VALUES (927,'Nippon Columbia');
INSERT INTO producers (id, name) VALUES (928,'Nippon Cultural Broadcasting');
INSERT INTO producers (id, name) VALUES (929,'Nippon Ichi Software');
INSERT INTO producers (id, name) VALUES (930,'Nippon Shuppan Hanbai (Nippan) K.K.');
INSERT INTO producers (id, name) VALUES (931,'Nippon Television Music');
INSERT INTO producers (id, name) VALUES (932,'Nippon Television Network');
INSERT INTO producers (id, name) VALUES (933,'Nishiki Studio');
INSERT INTO producers (id, name) VALUES (934,'Nishinippon Broadcasting');
INSERT INTO producers (id, name) VALUES (935,'Nitroplus');
INSERT INTO producers (id, name) VALUES (936,'Nobel');
INSERT INTO producers (id, name) VALUES (937,'nobishiro lab');
INSERT INTO producers (id, name) VALUES (938,'North Stars Pictures');
INSERT INTO producers (id, name) VALUES (939,'Notes');
INSERT INTO producers (id, name) VALUES (940,'NOTTV');
INSERT INTO producers (id, name) VALUES (941,'Nozomi Entertainment');
INSERT INTO producers (id, name) VALUES (942,'NTT Docomo');
INSERT INTO producers (id, name) VALUES (943,'NTT Plala');
INSERT INTO producers (id, name) VALUES (944,'OB Planning');
INSERT INTO producers (id, name) VALUES (945,'Obtain Future');
INSERT INTO producers (id, name) VALUES (946,'OCC');
INSERT INTO producers (id, name) VALUES (947,'Oddjob');
INSERT INTO producers (id, name) VALUES (948,'Office AO');
INSERT INTO producers (id, name) VALUES (949,'Office ENDLESS');
INSERT INTO producers (id, name) VALUES (950,'Office Nobu');
INSERT INTO producers (id, name) VALUES (951,'Oh! Production');
INSERT INTO producers (id, name) VALUES (952,'Okinawa Prefectural University of Arts');
INSERT INTO producers (id, name) VALUES (953,'OLE-M');
INSERT INTO producers (id, name) VALUES (954,'Olive Studio');
INSERT INTO producers (id, name) VALUES (955,'OLM');
INSERT INTO producers (id, name) VALUES (956,'Omnibus Japan');
INSERT INTO producers (id, name) VALUES (957,'On The Run');
INSERT INTO producers (id, name) VALUES (958,'On-Lead');
INSERT INTO producers (id, name) VALUES (959,'ONEMUSIC');
INSERT INTO producers (id, name) VALUES (960,'Ongaq');
INSERT INTO producers (id, name) VALUES (961,'ONIRO');
INSERT INTO producers (id, name) VALUES (962,'Opera House');
INSERT INTO producers (id, name) VALUES (963,'Orange');
INSERT INTO producers (id, name) VALUES (964,'Orchid Seed');
INSERT INTO producers (id, name) VALUES (965,'Oriental Creative Color');
INSERT INTO producers (id, name) VALUES (966,'Orix');
INSERT INTO producers (id, name) VALUES (967,'Osaka University of Arts');
INSERT INTO producers (id, name) VALUES (968,'Otogi Production');
INSERT INTO producers (id, name) VALUES (969,'Overlap');
INSERT INTO producers (id, name) VALUES (970,'Oz Inc.');
INSERT INTO producers (id, name) VALUES (971,'P Productions');
INSERT INTO producers (id, name) VALUES (972,'P-Vine Records');
INSERT INTO producers (id, name) VALUES (973,'P.A. Works');
INSERT INTO producers (id, name) VALUES (974,'P.I.C.S.');
INSERT INTO producers (id, name) VALUES (975,'Painted Blade Studio');
INSERT INTO producers (id, name) VALUES (976,'Pak Production');
INSERT INTO producers (id, name) VALUES (977,'Palm Studio');
INSERT INTO producers (id, name) VALUES (978,'Panasonic Digital Contents');
INSERT INTO producers (id, name) VALUES (979,'Panda Factory');
INSERT INTO producers (id, name) VALUES (980,'Panimation Hwakai Media');
INSERT INTO producers (id, name) VALUES (981,'PansonWorks');
INSERT INTO producers (id, name) VALUES (982,'Paper Plane Animation Studio');
INSERT INTO producers (id, name) VALUES (983,'Parco');
INSERT INTO producers (id, name) VALUES (984,'Pashmina');
INSERT INTO producers (id, name) VALUES (985,'Pastel');
INSERT INTO producers (id, name) VALUES (986,'Pazzy Entertainment');
INSERT INTO producers (id, name) VALUES (987,'Pb Animation Co. Ltd.');
INSERT INTO producers (id, name) VALUES (988,'Pencil');
INSERT INTO producers (id, name) VALUES (989,'Penta Show Studios');
INSERT INTO producers (id, name) VALUES (990,'Peter Pan Creation');
INSERT INTO producers (id, name) VALUES (991,'pH Studio');
INSERT INTO producers (id, name) VALUES (992,'Pia');
INSERT INTO producers (id, name) VALUES (993,'Picante Circus');
INSERT INTO producers (id, name) VALUES (994,'Picture Magic');
INSERT INTO producers (id, name) VALUES (995,'Pie in the sky');
INSERT INTO producers (id, name) VALUES (996,'Pierrot');
INSERT INTO producers (id, name) VALUES (997,'Pierrot Plus');
INSERT INTO producers (id, name) VALUES (998,'Pink Pineapple');
INSERT INTO producers (id, name) VALUES (999,'Pioneer LDC');
INSERT INTO producers (id, name) VALUES (1000,'Pixy');
INSERT INTO producers (id, name) VALUES (1001,'Planet');
INSERT INTO producers (id, name) VALUES (1002,'Planet Cartoon');
INSERT INTO producers (id, name) VALUES (1003,'Plus One');
INSERT INTO producers (id, name) VALUES (1004,'Po10tial');
INSERT INTO producers (id, name) VALUES (1005,'Polygon Magic');
INSERT INTO producers (id, name) VALUES (1006,'Polygon Pictures');
INSERT INTO producers (id, name) VALUES (1007,'Polygram Japan');
INSERT INTO producers (id, name) VALUES (1008,'Poncotan');
INSERT INTO producers (id, name) VALUES (1009,'Pony Canyon');
INSERT INTO producers (id, name) VALUES (1010,'Pony Canyon Enterprise');
INSERT INTO producers (id, name) VALUES (1011,'Poplar Publishing');
INSERT INTO producers (id, name) VALUES (1012,'PoPoCo');
INSERT INTO producers (id, name) VALUES (1013,'Postgal Workshop');
INSERT INTO producers (id, name) VALUES (1014,'PPP');
INSERT INTO producers (id, name) VALUES (1015,'PRA');
INSERT INTO producers (id, name) VALUES (1016,'Precious Tone');
INSERT INTO producers (id, name) VALUES (1017,'Presidio');
INSERT INTO producers (id, name) VALUES (1018,'Primastea');
INSERT INTO producers (id, name) VALUES (1019,'Procidis');
INSERT INTO producers (id, name) VALUES (1020,'Production Ace');
INSERT INTO producers (id, name) VALUES (1021,'Production GoodBook');
INSERT INTO producers (id, name) VALUES (1022,'Production I.G');
INSERT INTO producers (id, name) VALUES (1023,'Production Reed');
INSERT INTO producers (id, name) VALUES (1024,'project lights');
INSERT INTO producers (id, name) VALUES (1025,'Project No.9');
INSERT INTO producers (id, name) VALUES (1026,'Project Team Eikyuu Kikan');
INSERT INTO producers (id, name) VALUES (1027,'Project Team Sarah');
INSERT INTO producers (id, name) VALUES (1028,'PSG');
INSERT INTO producers (id, name) VALUES (1029,'Public & Basic');
INSERT INTO producers (id, name) VALUES (1030,'Pure Arts');
INSERT INTO producers (id, name) VALUES (1031,'Puzzle Animation Studio Limited');
INSERT INTO producers (id, name) VALUES (1032,'Pyramid');
INSERT INTO producers (id, name) VALUES (1033,'Q-Tec');
INSERT INTO producers (id, name) VALUES (1034,'Qiying Animation');
INSERT INTO producers (id, name) VALUES (1035,'Qiyuan Yinghua');
INSERT INTO producers (id, name) VALUES (1036,'Qizhiying Culture');
INSERT INTO producers (id, name) VALUES (1037,'QREAZY');
INSERT INTO producers (id, name) VALUES (1038,'QualiArts');
INSERT INTO producers (id, name) VALUES (1039,'Quaras');
INSERT INTO producers (id, name) VALUES (1040,'Quatre Stella');
INSERT INTO producers (id, name) VALUES (1041,'Quebico');
INSERT INTO producers (id, name) VALUES (1042,'Queen Bee');
INSERT INTO producers (id, name) VALUES (1043,'Quick Corporation');
INSERT INTO producers (id, name) VALUES (1044,'Quyue Technology');
INSERT INTO producers (id, name) VALUES (1045,'RAB Aomori Broadcasting');
INSERT INTO producers (id, name) VALUES (1046,'Radio Osaka');
INSERT INTO producers (id, name) VALUES (1047,'Radix');
INSERT INTO producers (id, name) VALUES (1048,'Rainbow Entertainment');
INSERT INTO producers (id, name) VALUES (1049,'Raku High Student Council');
INSERT INTO producers (id, name) VALUES (1050,'Rakuonsha');
INSERT INTO producers (id, name) VALUES (1051,'Rakuten');
INSERT INTO producers (id, name) VALUES (1052,'Rambling Records');
INSERT INTO producers (id, name) VALUES (1053,'RAMS');
INSERT INTO producers (id, name) VALUES (1054,'Rankin/Bass');
INSERT INTO producers (id, name) VALUES (1055,'Ranzai Studio');
INSERT INTO producers (id, name) VALUES (1056,'RAY');
INSERT INTO producers (id, name) VALUES (1057,'RCC Chugoku Broadcasting');
INSERT INTO producers (id, name) VALUES (1058,'REALCOFFEE ENTERTAINMENT');
INSERT INTO producers (id, name) VALUES (1059,'Rebrast');
INSERT INTO producers (id, name) VALUES (1060,'Red Dog Culture House');
INSERT INTO producers (id, name) VALUES (1061,'Remic');
INSERT INTO producers (id, name) VALUES (1062,'Rex Entertainment');
INSERT INTO producers (id, name) VALUES (1063,'Rialto Entertainment');
INSERT INTO producers (id, name) VALUES (1064,'Right Gauge');
INSERT INTO producers (id, name) VALUES (1065,'RightTracks');
INSERT INTO producers (id, name) VALUES (1066,'Rikuentai');
INSERT INTO producers (id, name) VALUES (1067,'Ripromo');
INSERT INTO producers (id, name) VALUES (1068,'Rironsha');
INSERT INTO producers (id, name) VALUES (1069,'RME');
INSERT INTO producers (id, name) VALUES (1070,'Robot Communications');
INSERT INTO producers (id, name) VALUES (1071,'Rock’n Roll Mountain');
INSERT INTO producers (id, name) VALUES (1072,'RoiVisual');
INSERT INTO producers (id, name) VALUES (1073,'Romantica club !!');
INSERT INTO producers (id, name) VALUES (1074,'Rondo Robe');
INSERT INTO producers (id, name) VALUES (1075,'Royal Limousine');
INSERT INTO producers (id, name) VALUES (1076,'RTHK');
INSERT INTO producers (id, name) VALUES (1077,'RX-RECORDS');
INSERT INTO producers (id, name) VALUES (1078,'Ryukyu Asahi Broadcasting');
INSERT INTO producers (id, name) VALUES (1079,'S-TAR7');
INSERT INTO producers (id, name) VALUES (1080,'Saban Brands');
INSERT INTO producers (id, name) VALUES (1081,'Saban Entertainment');
INSERT INTO producers (id, name) VALUES (1082,'Saber Links');
INSERT INTO producers (id, name) VALUES (1083,'Sakura Color Film');
INSERT INTO producers (id, name) VALUES (1084,'Sakura Create');
INSERT INTO producers (id, name) VALUES (1085,'Sakura Eiga-sha');
INSERT INTO producers (id, name) VALUES (1086,'Sakura Motion Picture');
INSERT INTO producers (id, name) VALUES (1087,'Sakura Production');
INSERT INTO producers (id, name) VALUES (1088,'SamBakZa');
INSERT INTO producers (id, name) VALUES (1089,'Samdo Film');
INSERT INTO producers (id, name) VALUES (1090,'Sammy');
INSERT INTO producers (id, name) VALUES (1091,'Samsara Animation Studio');
INSERT INTO producers (id, name) VALUES (1092,'Samsung');
INSERT INTO producers (id, name) VALUES (1093,'San-X');
INSERT INTO producers (id, name) VALUES (1094,'Sanctuary');
INSERT INTO producers (id, name) VALUES (1095,'SANDWICHWORKS');
INSERT INTO producers (id, name) VALUES (1096,'Sanfu Interactive Entertainment');
INSERT INTO producers (id, name) VALUES (1097,'Sankyo');
INSERT INTO producers (id, name) VALUES (1098,'Sankyo Planning');
INSERT INTO producers (id, name) VALUES (1099,'Sanrio');
INSERT INTO producers (id, name) VALUES (1100,'Sanrio Digital');
INSERT INTO producers (id, name) VALUES (1101,'Sanyo');
INSERT INTO producers (id, name) VALUES (1102,'Sanyo Bussan');
INSERT INTO producers (id, name) VALUES (1103,'SANZIGEN');
INSERT INTO producers (id, name) VALUES (1104,'Sapporo Television Broadcasting');
INSERT INTO producers (id, name) VALUES (1105,'Satelight');
INSERT INTO producers (id, name) VALUES (1106,'Sav! The World Productions');
INSERT INTO producers (id, name) VALUES (1107,'SB Creative');
INSERT INTO producers (id, name) VALUES (1108,'SBS TV Production');
INSERT INTO producers (id, name) VALUES (1109,'Scarlet');
INSERT INTO producers (id, name) VALUES (1110,'Schoolzone');
INSERT INTO producers (id, name) VALUES (1111,'Seasun Pictures');
INSERT INTO producers (id, name) VALUES (1112,'SEDIC International');
INSERT INTO producers (id, name) VALUES (1113,'Sega');
INSERT INTO producers (id, name) VALUES (1114,'Sega Games');
INSERT INTO producers (id, name) VALUES (1115,'Sega Interactive');
INSERT INTO producers (id, name) VALUES (1116,'Seikaisha');
INSERT INTO producers (id, name) VALUES (1117,'SEK Studios');
INSERT INTO producers (id, name) VALUES (1118,'SELFISH');
INSERT INTO producers (id, name) VALUES (1119,'Sentai Filmworks');
INSERT INTO producers (id, name) VALUES (1120,'Seta Corporation');
INSERT INTO producers (id, name) VALUES (1121,'Seven');
INSERT INTO producers (id, name) VALUES (1122,'Shaft');
INSERT INTO producers (id, name) VALUES (1123,'Shanghai Animation Film Studio');
INSERT INTO producers (id, name) VALUES (1124,'Shanghai Jump Network Technology');
INSERT INTO producers (id, name) VALUES (1125,'Shanghai Morejoy Entertainment Co.');
INSERT INTO producers (id, name) VALUES (1126,'Shanghai Tiantan Culture & Media');
INSERT INTO producers (id, name) VALUES (1127,'Sharefun Studio');
INSERT INTO producers (id, name) VALUES (1128,'Shelty');
INSERT INTO producers (id, name) VALUES (1129,'Shenfan Animation');
INSERT INTO producers (id, name) VALUES (1130,'Shengying Animation');
INSERT INTO producers (id, name) VALUES (1131,'Shimogumi');
INSERT INTO producers (id, name) VALUES (1132,'Shin-Ei Animation');
INSERT INTO producers (id, name) VALUES (1133,'Shinano Kikaku');
INSERT INTO producers (id, name) VALUES (1134,'Shinchosha');
INSERT INTO producers (id, name) VALUES (1135,'Shinkuukan');
INSERT INTO producers (id, name) VALUES (1136,'Shinshokan');
INSERT INTO producers (id, name) VALUES (1137,'Shinwon Productions');
INSERT INTO producers (id, name) VALUES (1138,'Shinyusha');
INSERT INTO producers (id, name) VALUES (1139,'Shirogumi');
INSERT INTO producers (id, name) VALUES (1140,'Shizuoka Asahi Television');
INSERT INTO producers (id, name) VALUES (1141,'Shizuoka Broadcasting System');
INSERT INTO producers (id, name) VALUES (1142,'Shizuoka Daiichi Television');
INSERT INTO producers (id, name) VALUES (1143,'Shochiku');
INSERT INTO producers (id, name) VALUES (1144,'Shochiku Media Division');
INSERT INTO producers (id, name) VALUES (1145,'Shochiku Music Publishing');
INSERT INTO producers (id, name) VALUES (1146,'Shodensha');
INSERT INTO producers (id, name) VALUES (1147,'Shogakukan');
INSERT INTO producers (id, name) VALUES (1148,'Shogakukan Music & Digital Entertainment');
INSERT INTO producers (id, name) VALUES (1149,'Shogakukan-Shueisha Productions');
INSERT INTO producers (id, name) VALUES (1150,'Shounen Gahousha');
INSERT INTO producers (id, name) VALUES (1151,'Show Corporation');
INSERT INTO producers (id, name) VALUES (1152,'Showgate');
INSERT INTO producers (id, name) VALUES (1153,'Showten');
INSERT INTO producers (id, name) VALUES (1154,'Shueisha');
INSERT INTO producers (id, name) VALUES (1155,'Shufu to Seikatsusha');
INSERT INTO producers (id, name) VALUES (1156,'Shufunotomo');
INSERT INTO producers (id, name) VALUES (1157,'Shun Produce');
INSERT INTO producers (id, name) VALUES (1158,'Silky’s');
INSERT INTO producers (id, name) VALUES (1159,'SILVER LINK.');
INSERT INTO producers (id, name) VALUES (1160,'Skouras');
INSERT INTO producers (id, name) VALUES (1161,'Sky Perfect Communications');
INSERT INTO producers (id, name) VALUES (1162,'SKY Perfect Well Think');
INSERT INTO producers (id, name) VALUES (1163,'SKY PerfecTV!');
INSERT INTO producers (id, name) VALUES (1164,'Slow Curve');
INSERT INTO producers (id, name) VALUES (1165,'SME Records');
INSERT INTO producers (id, name) VALUES (1166,'SME Visual Works');
INSERT INTO producers (id, name) VALUES (1167,'Smile Company');
INSERT INTO producers (id, name) VALUES (1168,'Smiral Animation');
INSERT INTO producers (id, name) VALUES (1169,'Soeishinsha');
INSERT INTO producers (id, name) VALUES (1170,'Soft Garage');
INSERT INTO producers (id, name) VALUES (1171,'Soft on Demand');
INSERT INTO producers (id, name) VALUES (1172,'SoftBank Creative');
INSERT INTO producers (id, name) VALUES (1173,'SoftX');
INSERT INTO producers (id, name) VALUES (1174,'Sogo Vision');
INSERT INTO producers (id, name) VALUES (1175,'Sol Blade');
INSERT INTO producers (id, name) VALUES (1176,'Sola Entertainment');
INSERT INTO producers (id, name) VALUES (1177,'Solid Vox');
INSERT INTO producers (id, name) VALUES (1178,'Sonilude');
INSERT INTO producers (id, name) VALUES (1179,'Sony Creative Products');
INSERT INTO producers (id, name) VALUES (1180,'Sony Interactive Entertainment');
INSERT INTO producers (id, name) VALUES (1181,'Sony Music Communications');
INSERT INTO producers (id, name) VALUES (1182,'Sony Music Entertainment');
INSERT INTO producers (id, name) VALUES (1183,'Sony Music Solutions');
INSERT INTO producers (id, name) VALUES (1184,'Sony PCL');
INSERT INTO producers (id, name) VALUES (1185,'Sony Pictures Entertainment');
INSERT INTO producers (id, name) VALUES (1186,'Sony Pictures Worldwide Acquisitions');
INSERT INTO producers (id, name) VALUES (1187,'Sotsu');
INSERT INTO producers (id, name) VALUES (1188,'Sotsu Music Publishing');
INSERT INTO producers (id, name) VALUES (1189,'Soular Animation Studio');
INSERT INTO producers (id, name) VALUES (1190,'Sound Team Don Juan');
INSERT INTO producers (id, name) VALUES (1191,'Souten no Ken');
INSERT INTO producers (id, name) VALUES (1192,'Soyuzmultfilm');
INSERT INTO producers (id, name) VALUES (1193,'Space Neko Company');
INSERT INTO producers (id, name) VALUES (1194,'Space Shower Music');
INSERT INTO producers (id, name) VALUES (1195,'Spacey Music Entertainment');
INSERT INTO producers (id, name) VALUES (1196,'Spectrum');
INSERT INTO producers (id, name) VALUES (1197,'SPEED');
INSERT INTO producers (id, name) VALUES (1198,'Speed Inc.');
INSERT INTO producers (id, name) VALUES (1199,'Splash Entertainment');
INSERT INTO producers (id, name) VALUES (1200,'SPO Entertainment');
INSERT INTO producers (id, name) VALUES (1201,'Square Enix');
INSERT INTO producers (id, name) VALUES (1202,'Starchild Records');
INSERT INTO producers (id, name) VALUES (1203,'Stardust Promotion');
INSERT INTO producers (id, name) VALUES (1204,'Starlight Entertainment');
INSERT INTO producers (id, name) VALUES (1205,'StarLink');
INSERT INTO producers (id, name) VALUES (1206,'Starry Cube');
INSERT INTO producers (id, name) VALUES (1207,'Stay Luck');
INSERT INTO producers (id, name) VALUES (1208,'Stella Promotion');
INSERT INTO producers (id, name) VALUES (1209,'Steve N'' Steven');
INSERT INTO producers (id, name) VALUES (1210,'STORY');
INSERT INTO producers (id, name) VALUES (1211,'Straight Edge');
INSERT INTO producers (id, name) VALUES (1212,'Strawberry Meets Pictures');
INSERT INTO producers (id, name) VALUES (1213,'Stray Cats');
INSERT INTO producers (id, name) VALUES (1214,'Streamline Pictures');
INSERT INTO producers (id, name) VALUES (1215,'Studio 1st');
INSERT INTO producers (id, name) VALUES (1216,'Studio 4°C');
INSERT INTO producers (id, name) VALUES (1217,'Studio A-CAT');
INSERT INTO producers (id, name) VALUES (1218,'Studio AWAKE');
INSERT INTO producers (id, name) VALUES (1219,'Studio Binzo');
INSERT INTO producers (id, name) VALUES (1220,'Studio Blanc.');
INSERT INTO producers (id, name) VALUES (1221,'Studio Cab');
INSERT INTO producers (id, name) VALUES (1222,'Studio Carbuncle');
INSERT INTO producers (id, name) VALUES (1223,'Studio Cats');
INSERT INTO producers (id, name) VALUES (1224,'Studio CHANT');
INSERT INTO producers (id, name) VALUES (1225,'Studio Comet');
INSERT INTO producers (id, name) VALUES (1226,'Studio Compile');
INSERT INTO producers (id, name) VALUES (1227,'Studio Core');
INSERT INTO producers (id, name) VALUES (1228,'Studio Curtain');
INSERT INTO producers (id, name) VALUES (1229,'Studio Dadashow');
INSERT INTO producers (id, name) VALUES (1230,'Studio Deen');
INSERT INTO producers (id, name) VALUES (1231,'Studio Deva Loka');
INSERT INTO producers (id, name) VALUES (1232,'Studio Easter');
INSERT INTO producers (id, name) VALUES (1233,'Studio Egg');
INSERT INTO producers (id, name) VALUES (1234,'Studio Elle');
INSERT INTO producers (id, name) VALUES (1235,'Studio Fantasia');
INSERT INTO producers (id, name) VALUES (1236,'Studio Flag');
INSERT INTO producers (id, name) VALUES (1237,'Studio G-1Neo');
INSERT INTO producers (id, name) VALUES (1238,'Studio G7');
INSERT INTO producers (id, name) VALUES (1239,'Studio Gokumi');
INSERT INTO producers (id, name) VALUES (1240,'Studio GOONEYS');
INSERT INTO producers (id, name) VALUES (1241,'Studio Gram');
INSERT INTO producers (id, name) VALUES (1242,'Studio Guts');
INSERT INTO producers (id, name) VALUES (1243,'Studio Hibari');
INSERT INTO producers (id, name) VALUES (1244,'Studio Izena');
INSERT INTO producers (id, name) VALUES (1245,'Studio Jack');
INSERT INTO producers (id, name) VALUES (1246,'Studio Junio');
INSERT INTO producers (id, name) VALUES (1247,'Studio Kaab');
INSERT INTO producers (id, name) VALUES (1248,'Studio Kai');
INSERT INTO producers (id, name) VALUES (1249,'Studio Kelmadick');
INSERT INTO producers (id, name) VALUES (1250,'Studio Kikan');
INSERT INTO producers (id, name) VALUES (1251,'Studio Kuma');
INSERT INTO producers (id, name) VALUES (1252,'Studio Kyuuma');
INSERT INTO producers (id, name) VALUES (1253,'Studio Liberty');
INSERT INTO producers (id, name) VALUES (1254,'Studio Live');
INSERT INTO producers (id, name) VALUES (1255,'Studio Lotus');
INSERT INTO producers (id, name) VALUES (1256,'Studio Massket');
INSERT INTO producers (id, name) VALUES (1257,'Studio Mausu');
INSERT INTO producers (id, name) VALUES (1258,'Studio Mir');
INSERT INTO producers (id, name) VALUES (1259,'Studio Montagne');
INSERT INTO producers (id, name) VALUES (1260,'Studio Moriken');
INSERT INTO producers (id, name) VALUES (1261,'Studio MWP');
INSERT INTO producers (id, name) VALUES (1262,'Studio N');
INSERT INTO producers (id, name) VALUES (1263,'Studio Nanahoshi');
INSERT INTO producers (id, name) VALUES (1264,'Studio Nem');
INSERT INTO producers (id, name) VALUES (1265,'Studio NOIX');
INSERT INTO producers (id, name) VALUES (1266,'Studio Nue');
INSERT INTO producers (id, name) VALUES (1267,'Studio PuYUKAI');
INSERT INTO producers (id, name) VALUES (1268,'Studio RE:Map');
INSERT INTO producers (id, name) VALUES (1269,'Studio Rikka');
INSERT INTO producers (id, name) VALUES (1270,'Studio Saki Makura');
INSERT INTO producers (id, name) VALUES (1271,'Studio Shamrock');
INSERT INTO producers (id, name) VALUES (1272,'Studio Sign');
INSERT INTO producers (id, name) VALUES (1273,'Studio Signal');
INSERT INTO producers (id, name) VALUES (1274,'Studio Take Off');
INSERT INTO producers (id, name) VALUES (1275,'Studio Tron');
INSERT INTO producers (id, name) VALUES (1276,'Studio Tulip');
INSERT INTO producers (id, name) VALUES (1277,'Studio Unicorn');
INSERT INTO producers (id, name) VALUES (1278,'Studio WHO');
INSERT INTO producers (id, name) VALUES (1279,'Studio Wombat');
INSERT INTO producers (id, name) VALUES (1280,'studio YOG');
INSERT INTO producers (id, name) VALUES (1281,'Studio Zain');
INSERT INTO producers (id, name) VALUES (1282,'Studio Zealot');
INSERT INTO producers (id, name) VALUES (1283,'Studio Zero');
INSERT INTO producers (id, name) VALUES (1284,'studioGONG');
INSERT INTO producers (id, name) VALUES (1285,'StudioRF Inc.');
INSERT INTO producers (id, name) VALUES (1286,'SUBARU');
INSERT INTO producers (id, name) VALUES (1287,'Success Corp.');
INSERT INTO producers (id, name) VALUES (1288,'Suiseisha');
INSERT INTO producers (id, name) VALUES (1289,'Sumitomo');
INSERT INTO producers (id, name) VALUES (1290,'Sumzap');
INSERT INTO producers (id, name) VALUES (1291,'Sun TV');
INSERT INTO producers (id, name) VALUES (1292,'Sunny Side Up');
INSERT INTO producers (id, name) VALUES (1293,'Sunrise');
INSERT INTO producers (id, name) VALUES (1294,'Sunrise Beyond');
INSERT INTO producers (id, name) VALUES (1295,'Sunrise Music');
INSERT INTO producers (id, name) VALUES (1296,'Sunwoo Entertainment');
INSERT INTO producers (id, name) VALUES (1297,'SUPA LOVE');
INSERT INTO producers (id, name) VALUES (1298,'syn Sophia');
INSERT INTO producers (id, name) VALUES (1299,'Synergy Japan');
INSERT INTO producers (id, name) VALUES (1300,'SynergySP');
INSERT INTO producers (id, name) VALUES (1301,'T-JOY');
INSERT INTO producers (id, name) VALUES (1302,'T.O Entertainment');
INSERT INTO producers (id, name) VALUES (1303,'T.P.O');
INSERT INTO producers (id, name) VALUES (1304,'Tablier Communications');
INSERT INTO producers (id, name) VALUES (1305,'Taikong Works');
INSERT INTO producers (id, name) VALUES (1306,'Takahashi Studio');
INSERT INTO producers (id, name) VALUES (1307,'Takara');
INSERT INTO producers (id, name) VALUES (1308,'Takara Tomy A.R.T.S');
INSERT INTO producers (id, name) VALUES (1309,'Takeshobo');
INSERT INTO producers (id, name) VALUES (1310,'TAKI Corporation');
INSERT INTO producers (id, name) VALUES (1311,'Takun Manga Box');
INSERT INTO producers (id, name) VALUES (1312,'Tama Production');
INSERT INTO producers (id, name) VALUES (1313,'Tamabi');
INSERT INTO producers (id, name) VALUES (1314,'tamakoshi');
INSERT INTO producers (id, name) VALUES (1315,'Tamura Shigeru Studio');
INSERT INTO producers (id, name) VALUES (1316,'TanKong Pictures');
INSERT INTO producers (id, name) VALUES (1317,'TAP');
INSERT INTO producers (id, name) VALUES (1318,'Tapioca');
INSERT INTO producers (id, name) VALUES (1319,'Tatsunoko Production');
INSERT INTO producers (id, name) VALUES (1320,'Tavac');
INSERT INTO producers (id, name) VALUES (1321,'TBS');
INSERT INTO producers (id, name) VALUES (1322,'TC Entertainment');
INSERT INTO producers (id, name) VALUES (1323,'TCJ');
INSERT INTO producers (id, name) VALUES (1324,'TEAM Entertainment Inc.');
INSERT INTO producers (id, name) VALUES (1325,'Techno Sound');
INSERT INTO producers (id, name) VALUES (1326,'Teichiku Entertainment');
INSERT INTO producers (id, name) VALUES (1327,'Tele-Cartoon Japan');
INSERT INTO producers (id, name) VALUES (1328,'Telecom Animation Film');
INSERT INTO producers (id, name) VALUES (1329,'Telescreen');
INSERT INTO producers (id, name) VALUES (1330,'TEM Co.');
INSERT INTO producers (id, name) VALUES (1331,'Tencent Animation & Comics');
INSERT INTO producers (id, name) VALUES (1332,'Tencent Games');
INSERT INTO producers (id, name) VALUES (1333,'Tencent Japan');
INSERT INTO producers (id, name) VALUES (1334,'Tencent Penguin Pictures');
INSERT INTO producers (id, name) VALUES (1335,'Tenkatsu Tennenshoku Katsudou Shashin');
INSERT INTO producers (id, name) VALUES (1336,'Terada Mokei');
INSERT INTO producers (id, name) VALUES (1337,'Tezuka Productions');
INSERT INTO producers (id, name) VALUES (1338,'The Answer Studio');
INSERT INTO producers (id, name) VALUES (1339,'The Berich');
INSERT INTO producers (id, name) VALUES (1340,'The Gate Studio');
INSERT INTO producers (id, name) VALUES (1341,'The National Film Center Japan');
INSERT INTO producers (id, name) VALUES (1342,'The Village of Marchen');
INSERT INTO producers (id, name) VALUES (1343,'THINGS.');
INSERT INTO producers (id, name) VALUES (1344,'Think Corporation');
INSERT INTO producers (id, name) VALUES (1345,'THINKR');
INSERT INTO producers (id, name) VALUES (1346,'Three Fat Samurai');
INSERT INTO producers (id, name) VALUES (1347,'Tianshi Wenhua');
INSERT INTO producers (id, name) VALUES (1348,'Tianwen Kadokawa Animation & Comics');
INSERT INTO producers (id, name) VALUES (1349,'TiMi Studio Group');
INSERT INTO producers (id, name) VALUES (1350,'Tin House');
INSERT INTO producers (id, name) VALUES (1351,'TIS');
INSERT INTO producers (id, name) VALUES (1352,'TMS Entertainment');
INSERT INTO producers (id, name) VALUES (1353,'TMS Music');
INSERT INTO producers (id, name) VALUES (1354,'TMS-Kyokuchi');
INSERT INTO producers (id, name) VALUES (1355,'TO Books');
INSERT INTO producers (id, name) VALUES (1356,'Tochigi TV');
INSERT INTO producers (id, name) VALUES (1357,'Toei Advertising');
INSERT INTO producers (id, name) VALUES (1358,'Toei Animation');
INSERT INTO producers (id, name) VALUES (1359,'Toei Video');
INSERT INTO producers (id, name) VALUES (1360,'Tohan Corporation');
INSERT INTO producers (id, name) VALUES (1361,'Tohjak');
INSERT INTO producers (id, name) VALUES (1362,'Toho');
INSERT INTO producers (id, name) VALUES (1363,'TOHO animation');
INSERT INTO producers (id, name) VALUES (1364,'Toho Interactive Animation');
INSERT INTO producers (id, name) VALUES (1365,'Toho Music');
INSERT INTO producers (id, name) VALUES (1366,'Toho Visual Entertainment');
INSERT INTO producers (id, name) VALUES (1367,'Tohoku University of Art and Design');
INSERT INTO producers (id, name) VALUES (1368,'Tohokushinsha Film Corporation');
INSERT INTO producers (id, name) VALUES (1369,'Tokai Television');
INSERT INTO producers (id, name) VALUES (1370,'Tokuma Japan');
INSERT INTO producers (id, name) VALUES (1371,'Tokuma Japan Communications');
INSERT INTO producers (id, name) VALUES (1372,'Tokuma Shoten');
INSERT INTO producers (id, name) VALUES (1373,'Tokyo Animation Film');
INSERT INTO producers (id, name) VALUES (1374,'Tokyo Animator Gakuin');
INSERT INTO producers (id, name) VALUES (1375,'Tokyo FM Broadcasting');
INSERT INTO producers (id, name) VALUES (1376,'Tokyo Kids');
INSERT INTO producers (id, name) VALUES (1377,'Tokyo Movie Shinsha');
INSERT INTO producers (id, name) VALUES (1378,'Tokyo MX');
INSERT INTO producers (id, name) VALUES (1379,'Tokyo Polytechnic University');
INSERT INTO producers (id, name) VALUES (1380,'Tokyo Theatres');
INSERT INTO producers (id, name) VALUES (1381,'Tokyo Zokei University');
INSERT INTO producers (id, name) VALUES (1382,'Tokyu Recreation');
INSERT INTO producers (id, name) VALUES (1383,'Tomoyasu Murata Company');
INSERT INTO producers (id, name) VALUES (1384,'TOMY Company');
INSERT INTO producers (id, name) VALUES (1385,'Tonko House');
INSERT INTO producers (id, name) VALUES (1386,'Top Marshal');
INSERT INTO producers (id, name) VALUES (1387,'Top-Insight International');
INSERT INTO producers (id, name) VALUES (1388,'Topcraft');
INSERT INTO producers (id, name) VALUES (1389,'Toppan Printing');
INSERT INTO producers (id, name) VALUES (1390,'Toranoana');
INSERT INTO producers (id, name) VALUES (1391,'Tose');
INSERT INTO producers (id, name) VALUES (1392,'Toshiba Digital Frontiers');
INSERT INTO producers (id, name) VALUES (1393,'Toshiba EMI');
INSERT INTO producers (id, name) VALUES (1394,'Toshiba Entertainment');
INSERT INTO producers (id, name) VALUES (1395,'Tosho Printing');
INSERT INTO producers (id, name) VALUES (1396,'Tower Records');
INSERT INTO producers (id, name) VALUES (1397,'Toy''s Factory');
INSERT INTO producers (id, name) VALUES (1398,'Toyo Links Corporation');
INSERT INTO producers (id, name) VALUES (1399,'Toyo Recording');
INSERT INTO producers (id, name) VALUES (1400,'Trans Arts');
INSERT INTO producers (id, name) VALUES (1401,'Trans Cosmos');
INSERT INTO producers (id, name) VALUES (1402,'Trash Studio');
INSERT INTO producers (id, name) VALUES (1403,'Triangle Staff');
INSERT INTO producers (id, name) VALUES (1404,'Trick Block');
INSERT INTO producers (id, name) VALUES (1405,'TriF Studio');
INSERT INTO producers (id, name) VALUES (1406,'Trigger');
INSERT INTO producers (id, name) VALUES (1407,'Trilogy Future Studio');
INSERT INTO producers (id, name) VALUES (1408,'Trinet Entertainment');
INSERT INTO producers (id, name) VALUES (1409,'Trinity Sound');
INSERT INTO producers (id, name) VALUES (1410,'TRUSS');
INSERT INTO producers (id, name) VALUES (1411,'Tsubasa Entertainment');
INSERT INTO producers (id, name) VALUES (1412,'Tsuburaya Productions');
INSERT INTO producers (id, name) VALUES (1413,'Tsuchida Productions');
INSERT INTO producers (id, name) VALUES (1414,'Tsukuru no Mori');
INSERT INTO producers (id, name) VALUES (1415,'TSUTAYA');
INSERT INTO producers (id, name) VALUES (1416,'TUBA');
INSERT INTO producers (id, name) VALUES (1417,'TV Aichi');
INSERT INTO producers (id, name) VALUES (1418,'TV Asahi');
INSERT INTO producers (id, name) VALUES (1419,'TV Asahi Music');
INSERT INTO producers (id, name) VALUES (1420,'TV Kanagawa');
INSERT INTO producers (id, name) VALUES (1421,'TV Osaka');
INSERT INTO producers (id, name) VALUES (1422,'TV Saitama');
INSERT INTO producers (id, name) VALUES (1423,'TV Setouchi');
INSERT INTO producers (id, name) VALUES (1424,'TV Tokyo');
INSERT INTO producers (id, name) VALUES (1425,'TV Tokyo Communications');
INSERT INTO producers (id, name) VALUES (1426,'TV Tokyo Music');
INSERT INTO producers (id, name) VALUES (1427,'TVA advance');
INSERT INTO producers (id, name) VALUES (1428,'Twin Engine');
INSERT INTO producers (id, name) VALUES (1429,'Twin Planet');
INSERT INTO producers (id, name) VALUES (1430,'TYO');
INSERT INTO producers (id, name) VALUES (1431,'TYO Animations');
INSERT INTO producers (id, name) VALUES (1432,'Typhoon Graphics');
INSERT INTO producers (id, name) VALUES (1433,'U-NEXT');
INSERT INTO producers (id, name) VALUES (1434,'U/M/A/A Inc.');
INSERT INTO producers (id, name) VALUES (1435,'UK.PROJECT INC.');
INSERT INTO producers (id, name) VALUES (1436,'Ultra Super Pictures');
INSERT INTO producers (id, name) VALUES (1437,'UM Productions');
INSERT INTO producers (id, name) VALUES (1438,'Union Cho');
INSERT INTO producers (id, name) VALUES (1439,'Universal Entertainment');
INSERT INTO producers (id, name) VALUES (1440,'Universal Music Japan');
INSERT INTO producers (id, name) VALUES (1441,'Universal Pictures Japan');
INSERT INTO producers (id, name) VALUES (1442,'Universal Radio Studio');
INSERT INTO producers (id, name) VALUES (1443,'Universal Studios');
INSERT INTO producers (id, name) VALUES (1444,'UNKNOWN');
INSERT INTO producers (id, name) VALUES (1445,'Usagi Ou');
INSERT INTO producers (id, name) VALUES (1446,'USAGI Production');
INSERT INTO producers (id, name) VALUES (1447,'USEN');
INSERT INTO producers (id, name) VALUES (1448,'USERJOY Technology');
INSERT INTO producers (id, name) VALUES (1449,'Valkyria');
INSERT INTO producers (id, name) VALUES (1450,'Vanikey');
INSERT INTO producers (id, name) VALUES (1451,'VAP');
INSERT INTO producers (id, name) VALUES (1452,'Vasoon Animation');
INSERT INTO producers (id, name) VALUES (1453,'Vega Entertainment');
INSERT INTO producers (id, name) VALUES (1454,'Venus Vangard');
INSERT INTO producers (id, name) VALUES (1455,'Victor Entertainment');
INSERT INTO producers (id, name) VALUES (1456,'Victor Studio');
INSERT INTO producers (id, name) VALUES (1457,'Video Market');
INSERT INTO producers (id, name) VALUES (1458,'Viki');
INSERT INTO producers (id, name) VALUES (1459,'Village Studio');
INSERT INTO producers (id, name) VALUES (1460,'Virgin Babylon Records');
INSERT INTO producers (id, name) VALUES (1461,'Visual 80');
INSERT INTO producers (id, name) VALUES (1462,'Visual Arts');
INSERT INTO producers (id, name) VALUES (1463,'Visual Vision');
INSERT INTO producers (id, name) VALUES (1464,'Vobile Japan');
INSERT INTO producers (id, name) VALUES (1465,'Volks');
INSERT INTO producers (id, name) VALUES (1466,'VOOZ Character System');
INSERT INTO producers (id, name) VALUES (1467,'voque ting');
INSERT INTO producers (id, name) VALUES (1468,'Voyager Entertainment');
INSERT INTO producers (id, name) VALUES (1469,'VV-ALKLINE');
INSERT INTO producers (id, name) VALUES (1470,'W-Toon Studio');
INSERT INTO producers (id, name) VALUES (1471,'Wako Productions');
INSERT INTO producers (id, name) VALUES (1472,'Walkers Company');
INSERT INTO producers (id, name) VALUES (1473,'Walt Disney Japan');
INSERT INTO producers (id, name) VALUES (1474,'Wanda Media');
INSERT INTO producers (id, name) VALUES (1475,'WAO World');
INSERT INTO producers (id, name) VALUES (1476,'Wargaming Japan');
INSERT INTO producers (id, name) VALUES (1477,'Warner Bros. Japan');
INSERT INTO producers (id, name) VALUES (1478,'Warner Music Japan');
INSERT INTO producers (id, name) VALUES (1479,'WarRock');
INSERT INTO producers (id, name) VALUES (1480,'Watanabe Promotion');
INSERT INTO producers (id, name) VALUES (1481,'Watermark');
INSERT INTO producers (id, name) VALUES (1482,'Wave Master');
INSERT INTO producers (id, name) VALUES (1483,'Welz Animation Studios');
INSERT INTO producers (id, name) VALUES (1484,'WField');
INSERT INTO producers (id, name) VALUES (1485,'Whatever Co.');
INSERT INTO producers (id, name) VALUES (1486,'White Bear');
INSERT INTO producers (id, name) VALUES (1487,'White Fox');
INSERT INTO producers (id, name) VALUES (1488,'Wicky.Records');
INSERT INTO producers (id, name) VALUES (1489,'Winfuture Media');
INSERT INTO producers (id, name) VALUES (1490,'Wit Studio');
INSERT INTO producers (id, name) VALUES (1491,'Wolf Smoke Studio');
INSERT INTO producers (id, name) VALUES (1492,'Wolfsbane');
INSERT INTO producers (id, name) VALUES (1493,'Wonder Cat Animation');
INSERT INTO producers (id, name) VALUES (1494,'Wonder Kids');
INSERT INTO producers (id, name) VALUES (1495,'World Cosplay Summit');
INSERT INTO producers (id, name) VALUES (1496,'WOWMAX');
INSERT INTO producers (id, name) VALUES (1497,'WOWOW');
INSERT INTO producers (id, name) VALUES (1498,'Wright Staff');
INSERT INTO producers (id, name) VALUES (1499,'Xebec');
INSERT INTO producers (id, name) VALUES (1500,'XFLAG');
INSERT INTO producers (id, name) VALUES (1501,'XFLAG Pictures');
INSERT INTO producers (id, name) VALUES (1502,'Xiaoming Taiji');
INSERT INTO producers (id, name) VALUES (1503,'Xing');
INSERT INTO producers (id, name) VALUES (1504,'Xuanshi Tangmen');
INSERT INTO producers (id, name) VALUES (1505,'Xuanyuan Network');
INSERT INTO producers (id, name) VALUES (1506,'Y&N Brothers');
INSERT INTO producers (id, name) VALUES (1507,'Yahoo! Japan');
INSERT INTO producers (id, name) VALUES (1508,'Yamaha Music Communications');
INSERT INTO producers (id, name) VALUES (1509,'Yamamura Animation');
INSERT INTO producers (id, name) VALUES (1510,'Yamasa');
INSERT INTO producers (id, name) VALUES (1511,'Yamato Works');
INSERT INTO producers (id, name) VALUES (1512,'Yaoqi');
INSERT INTO producers (id, name) VALUES (1513,'Year Young Culture');
INSERT INTO producers (id, name) VALUES (1514,'Yellow Film');
INSERT INTO producers (id, name) VALUES (1515,'Yi Animation');
INSERT INTO producers (id, name) VALUES (1516,'Yikuiduo Animation');
INSERT INTO producers (id, name) VALUES (1517,'Yili Animation Studio');
INSERT INTO producers (id, name) VALUES (1518,'Yokohama Animation Lab');
INSERT INTO producers (id, name) VALUES (1519,'Yomiko Advertising');
INSERT INTO producers (id, name) VALUES (1520,'Yomiuri Advertising');
INSERT INTO producers (id, name) VALUES (1521,'Yomiuri Shimbun');
INSERT INTO producers (id, name) VALUES (1522,'Yomiuri Telecasting');
INSERT INTO producers (id, name) VALUES (1523,'Yomiuri TV Enterprise');
INSERT INTO producers (id, name) VALUES (1524,'Yoon''s Color');
INSERT INTO producers (id, name) VALUES (1525,'Yoshimoto Creative Agency');
INSERT INTO producers (id, name) VALUES (1526,'Yoshimoto Kogyo');
INSERT INTO producers (id, name) VALUES (1527,'Yostar');
INSERT INTO producers (id, name) VALUES (1528,'Yostar Pictures');
INSERT INTO producers (id, name) VALUES (1529,'Youku');
INSERT INTO producers (id, name) VALUES (1530,'Youliao Studio');
INSERT INTO producers (id, name) VALUES (1531,'Youmex');
INSERT INTO producers (id, name) VALUES (1532,'Youth Film Studio');
INSERT INTO producers (id, name) VALUES (1533,'YTV');
INSERT INTO producers (id, name) VALUES (1534,'Yuewen Animation & Comics');
INSERT INTO producers (id, name) VALUES (1535,'Yuhodo');
INSERT INTO producers (id, name) VALUES (1536,'YUKE''S');
INSERT INTO producers (id, name) VALUES (1537,'Yumearu');
INSERT INTO producers (id, name) VALUES (1538,'Yumeta Company');
INSERT INTO producers (id, name) VALUES (1539,'Yunyi Animation');
INSERT INTO producers (id, name) VALUES (1540,'YURUPPE Inc.');
INSERT INTO producers (id, name) VALUES (1541,'Zack Promotion');
INSERT INTO producers (id, name) VALUES (1542,'Zelico Film');
INSERT INTO producers (id, name) VALUES (1543,'ZERO-A');
INSERT INTO producers (id, name) VALUES (1544,'Zero-G');
INSERT INTO producers (id, name) VALUES (1545,'Zexcs');
INSERT INTO producers (id, name) VALUES (1546,'Zhou Shen Studio');
INSERT INTO producers (id, name) VALUES (1547,'Zipang');
INSERT INTO producers (id, name) VALUES (1548,'ZIZ Entertainment (ZIZ)');
INSERT INTO producers (id, name) VALUES (1549,'ZOOM ENTERPRISE');

-- migrate:down 

DELETE FROM producers;